### ISSUE TITLE
PostgREST + PgBouncer - How to use different pool methods in PostgREST?

### ISSUE THREAD

**Issue by karrapetta** [PostgREST/postgrest#1011]
Hi,

We're using PostgREST with PgBouncer in our project.

PgBouncer pooling supports Session, Transaction or Statement.  (pgbouncer.github.io/usage.html)

We tested only changing the pool mode in pgBouncer to Transaction or Statement, and it occurred the error bellow:
{"hint":null,"details":null,"code":"42P05","message":"prepared statement "0" already exists"}

We need to know how to use transaction or statement pooling in PostgREST, due to the number of requests we made.

Could anyone help us?

Thanks.
Rodrigo C Souza

**Comment by ruslantalpa** [comment]
what are you using pgbouncer for?

**Comment by begriffs** [comment]
It looks like the hasql-postgres library may have a counter it uses to name prepared statements, and that counter isn't getting incremented? https://github.com/nikita-volkov/hasql-postgres/blob/5c815ec13655b7d49b3d727ab4303ea41f18f7b1/library/Hasql/Postgres/Session/Execution.hs#L55

Maybe it's the way we're calling the library, or an interaction with connection pooling.

@nikita-volkov can you advise?

**Comment by nikita-volkov** [comment]
Are you sure you're using "hasql-postgres"? That library was deprecated ages ago in favor of just "hasql". But yes, we do name the prepared statements the same way in the present versions.

It's not clear to me what the issue here is though.

**Comment by nikita-volkov** [comment]
Are you sure you're using "hasql-postgres"? That library was deprecated ages ago in favor of just "hasql". But yes, we do name the prepared statements the same way in the present versions.

It's not clear to me what the issue here is though.

**Comment by guiuprado** [comment]
Hi everyone.
Some good reason it's in production cases with or without cluster or citusdata, the pgbouncer or other pool manger service can help to optimize the use of active and idles connections. Mostly cases when several applications with pool enabled tend to access the PostgresSQL not only the PostgrREST. Actually we currently use exactly this way. So to both work together we need to set the pgbouncer mode to session. The session is less optimized method and tends to maintain the connection open until the caller close or timeout is hit. In critical environment it's not allowed.
Thanks for great job!! PostgREST is amazing. Thanks.

**Comment by ruslantalpa** [comment]
if you have a single database server then i don't see why you need pgbouncer.
PostgREST already maintains it's own connection pool (connections are being reused).

**Comment by guiuprado** [comment]
Hi everyone;

@ruslantalpa, the pgBouncer is not only used for proxy multiples postgres database, it's use for manager the connection pool on hight concurrence pool scenarios. For exemple, my Postgres can handle max 100 connections. But I have not only postgrest, but multiples postgrest for others api, all using the same Postgres, other applications, build in .netcore, a geoserver, some others clients IDE like QuantumGIS, Dashboards with Syncfusion Dash. So we can't remove pgBouncer of this equation because Postgres can't handle properly all this client, exactly because of this maintains of connections, every open connection, or unclosed, "locked" or "reduce" the free spots on pool. Because of this we can allow anybody connect directly to Postgres without pgBouncer.
But I believe the question is more about if PostgREST can be use with pgBouncer, indeed they can, but only in session mode. I to believe the @begriffs identify the problem, so it's possible we have some fix around new versions.
Thanks.

**Comment by begriffs** [comment]
@guiuprado glad session pooling works. If we can make sure the prepared statement identifier is unique we should probably be able to support transaction pooling, I think we're within the acceptable [SQL features](https://wiki.postgresql.org/wiki/PgBouncer#Feature_matrix_for_pooling_modes) for transaction pooling. (We use `SET LOCAL` rather than `SET` for variables.)

I wonder what the recommendation should be for using PostgREST with pgBouncer? For instance, would session- or transaction-pooling be best, and how large should our own pool be, and how long should items in our pool remain connected to pgBouncer on idle?

For context, each client API request runs in a single transaction, pulling a connection out of the internal pool, doing the transaction, and puting the connection back in the pool.

**Comment by guiuprado** [comment]
Hi @begriffs sorry for delay. Thanks for your return. Actually we set 1000 connections. The idle time is about 1min,  for now we can use only the session because we don't setup a building environment, but I believe using transaction will be better for the all "ecosystem". Ours server run with 24cpus, 32gb ram, and some table's with millions of data.
We have a 3 services set, 1) exyension partman, 2) extesion jobmon, 3) our api. The api is use to persist and retriever data for a data lead system we trying to build. So huge json are send to a nginx proxy, so the they send to the PostgrREST. The next version we pretending to send csv.
We send json with 20 to 30 attributes with 200k lines. Is pretty impressive the power of PostgREST.
If you want I can tell more about your architecture so if you can talk about it's going right or simply give us your opinion.
Thanks.

**Comment by steve-chavez** [comment]
Might be possible to use PgBouncer transaction pooling with the patch in https://github.com/PostgREST/postgrest/pull/1542#issuecomment-646081703.

**Comment by laurenceisla** [comment]
Transaction pooling is now compatible after commit db95bd1c3733eb979f4a65b3df0eaa16cadb4df2.
