### ISSUE TITLE
Support Heroku Postgres out of the box

### ISSUE THREAD

**Issue by zharikovpro** [PostgREST/postgrest#1050]
PostgREST uses DB_URI env var to read connection string, but Heroku Postgres stores connection string in DATABASE_URL.  Reading connection string from that var would make Heroku Button a joy to use with Heroku Postgres!

Simply copying DATABASE_URL content to DB_URI is not enough, cause Heroku may rotate credentials and update connection string. Also, DB owner can force credentials rotation, too.

Possible solutions that I see:

a) try to read connection string first from DATABASE_URL, then from DB_URI.

b) introduce DB_VAR_NAME (or similar) option with "DATABASE_URL" as default for the new buildpack version and "DB_URI" if missing. That way old installations will work as before, and new installations will support Heroku Postgres out of the box, and other DB providers, too.

I'm not proficient in Haskell to implement it myself, yet will gladly sponsor this feature implementation if you approve it.

**Comment by begriffs** [comment]
The big reason we haven't integrated with Heroku Postgres is because it doesn't offer admins the permissions to create new database roles. Roles are the basis for how we do [access permissions](https://postgrest.com/en/v4.4/auth.html), so at the moment Heroku Postgres is suitable only for apps where every API client has the same level of access.

If Heroku relaxes this restriction then I'm all for making it easier for a PostgREST server to connect to the built-in db, but [this section](https://devcenter.heroku.com/articles/heroku-postgresql#connection-permissions) in the Heroku docs points against it.

**Comment by zharikovpro** [comment]
On professional plans Heroku to [add roles via dashboard/cli](https://devcenter.heroku.com/articles/heroku-postgresql-credentials). That way app can have many roles with different access rules. 

For sure, each user won't have a unique role (as Heroku doesn't allow to execute SQL to create roles). Yet, it's rarely needed to create a role for each individual user. 

It's possible to create "anonymous", "webapi", "admin", "cron", etc roles. Perfect fit for RBAC! For many apps (especially in the MVP stage, like for my projects) it will be more than enough to leverage PostgREST.

Regarding "connection permissions" section: it's possible to create a credential (role) with read-only permissions by default, and then execute an arbitrary number of SQL commands with "GRANT" [to shape role permissions](https://devcenter.heroku.com/articles/heroku-postgresql-credentials#managing-permissions).

**Comment by begriffs** [comment]
@boblauer if you'd like to sponsor this work I can work on improving Heroku support. (I'm not willing to work on this issue for free due to a new [personal policy](https://begriffs.com/posts/2018-04-01-no-more-freebies.html))

**Comment by boblauer** [comment]
I ended up forking the postgres-heroku application and adding the following to the `env-to-config` file:

```bash
# Get DATABASE_URL explicitly, as it is populated by Heroku automatically
if [ "$DATABASE_URL" ]; then
  echo "db-uri=\"${DATABASE_URL}\"" >> $CONF_PATH
fi
```

Perhaps not the most elegant solution, but it worked perfectly.

**Comment by steve-chavez** [comment]
To add the possibility of using heroku postgres, we would need to add some logic(in the postgrest-heroku repo) to make sure that the db is in a "premium" tier and disallow free tier ones, also we'd need a section in the docs about how to handle roles in heroku.

If someone wants this sooner rather than later consider sponsoring the feature on PostgREST's [Patreon](https://www.patreon.com/postgrest).

**Comment by steve-chavez** [comment]
Moving this to https://github.com/PostgREST/postgrest-heroku/issues/16.
