### ISSUE TITLE
Updating app using postgrest-heroku's buildpack

### ISSUE THREAD

**Issue by ACPK** [PostgREST/postgrest#1066]
Is upgrading Postgrest is as easy as changing the "POSTGREST_VER" ENV? I'm assuming there will be breaking changes as it's not at 1.0 yet.  :)

**Comment by steve-chavez** [comment]
Since `v0.4` we use a file for the configuration and this will continue to be backwards compatible for upcoming releases.

Right now just changing the `POSTGREST_VER` env var won't upgrade to a new version, that's because the previous version binary remains cached, this logic could be changed to clear the cache, download the new version and cache it. Consider supporting PostgREST on [Patreon](https://www.patreon.com/postgrest) so I can dedicate time into adding this new logic.

**Comment by steve-chavez** [comment]
Fixed in https://github.com/PostgREST/postgrest-heroku/pull/24.
