### ISSUE TITLE
How to run two instances of postgrest with different databases and api domains

### ISSUE THREAD

**Issue by dnielrodrigues** [PostgREST/postgrest#1090]
When i tried run the postgrest.conf file with:
``` server-host = "mydomain.com.br" ```

The error:
```
postgrest: Network.Socket.getAddrInfo: does not exist (Name or service not known)
```
Without server-host param it works normaly, but a i need to run many domains with different databases, schemas, etc...

**Comment by ruslantalpa** [comment]
server-host is not important, you need to change the port parameter for each instance

**Comment by steve-chavez** [comment]
The `server-host` is the address where to bind the pgrst web server(defaults to `127.0.0.1` that's why it works without it), see the docs https://postgrest.com/en/v4.4/install.html#configuration on that.

For multiple databases you need multiple instances of pgrst, if they're on the same domain you'll need to handle the locations with `nginx/openresty`(pgrst relies on the proxy for this kind of use cases, see https://postgrest.com/en/v4.4/intro.html#one-thing-well).

For multiple schemas currently the handling will be the same as for multiple databases, but there is the possibility of improving the `db-schema` config parameter to allow many schemas, this was discussed in #1003.

**Comment by dnielrodrigues** [comment]
Thanks for your answers... But...
Guys, i think that you are dont see the real situation... see:

for sample, using nginx to set:
mydomainA.com.br for postgrest in localhost:3000
mydomainB.com.br for postgrest in localhost:3001
mydomainC.com.br for postgrest in localhost:3002

this is a ball of mud... dont?????
AND SEE:
Actually in postgrest IS NOT POSSIBLE to set (in the SAME server):
mydomainA.com.br for postgrest in mydomainA.com.br:3000
mydomainB.com.br for postgrest in mydomainB.com.br:3000
mydomainC.com.br for postgrest in mydomainC.com.br:3000

And this is what our project need...
Is for that reason: im question if somebody can develop this new feature and HOW MUCH??????

**Comment by ruslantalpa** [comment]
well..., your big ball of mud was created by the person who decided to have a separate database instance for each client ... so :)
in the end, it's as simple as this: for each database instance, you need one postgrest instance running. The number of postgrest instances needed is not a consequence of the number of clients, but the number of databases running.

However... if you have multiple clients hosted in the same database (and separated into schemas), it is possible to have a single postgrest for this type of setup, and we can talk about that type of "multi-tenency".

**Comment by steve-chavez** [comment]
Mapping databases to subdomains is outside of the scope of PostgREST, that should be done at the proxy level(Nginx, Caddy, etc). About schema based multi-tenancy with a single PostgREST instance, we can continue that discussion in #1106.
