### ISSUE TITLE
jwt-secret do not work

### ISSUE THREAD

**Issue by iaskwho** [PostgREST/postgrest#1123]
### Environment

* PostgreSQL version: 9.6 10.4
* PostgREST version: v0.5.0.0
* Operating system: mac and windows

### Description of issue
i touch a config like this:
db-uri = "postgres://postgres:123456@localhost:5432/postgres"
db-schema = "api"
db-anon-role = "todo_user"
db-pool = 1  
server-host = "*4"
server-port = 3000
jwt-secret = "jfdsfkdfjdlsfjkdlsjfldsfklsfjlsdfldfjldskfsdkfjfjdslf"

but when i start command: postgrest config.conf，and post insert data to demo table "todos" without Authorization header， it still insert success。
![image](https://user-images.githubusercontent.com/6389808/40634874-e1b99148-6329-11e8-8f58-5a32398d6bae.png)
 
(Expected behavior vs actual behavior)

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)

**Comment by steve-chavez** [comment]
PostgREST works with Bearer tokens, when you include the header like `Authorization: fdas fdas` PostgREST will ignore it(not a bearer token) and default to the anon role, in your case `todo_user` which I guess has INSERT permissions on the `todos` table(paste `\z todos` output to confirm), that's why it succeeds.

If you had `Authorization: Bearer fdas fdas` then you would get a JWT decoding error.

**Comment by steve-chavez** [comment]
The `db-anon-role` shouldn't be high privileged, you usually will have an `anon` role that has at most `SELECT` permissions, you can follow the tutorial https://postgrest.org/en/v5.0/tutorials/tut0.html#step-4-create-database-for-api for more detailed instructions.

**Comment by iaskwho** [comment]
thanks! @steve-chavez

**Comment by steve-chavez** [comment]
Ok, I'll consider this resolved then, reopen if not.
