### ISSUE TITLE
Alpine 3.7 Docker image with PostgREST 0.5.0.0

### ISSUE THREAD

**Issue by mcarans** [PostgREST/postgrest#1143]
For those interested, I have made a Docker image for Alpine 3.7 and PostgREST 0.5.0.0.

It is here: https://hub.docker.com/r/mcarans/alpine-haskell-postgrest/

Dockerfile etc. are here: https://github.com/OCHA-DAP/alpine-haskell-postgrest

**Comment by steve-chavez** [comment]
Just to restate why we don't offer an official alpine image:

**We discourage building and using PostgREST on Alpine Linux because of a reported GHC memory leak on that platform**.

This is mentioned in the docs, also a previous discussion in #867.

Now, if this is not the case with newer Alpine images(would have to test that), I guess we could make Alpine a target of our release pipeline but for now I recommend just using the official docker image https://hub.docker.com/r/postgrest/postgrest/.

**Comment by steve-chavez** [comment]
I'll close this for now. Users can find the alpine image by searching the issues.
