### ISSUE TITLE
Hackage still serves 0.4.4 instead of 0.5

### ISSUE THREAD

**Issue by uskudnik** [PostgREST/postgrest#1146]
Hackage lists [0.4.4.0](http://hackage.haskell.org/package/postgrest) as version of postgREST while release seems to be at 0.5.0.0.

Looked through issues and couldn't find mention of 0.5.0.0 but it seems it happened before so maybe this would be a good addition to postgrest-bot (or something similar if you have it)?

**Comment by begriffs** [comment]
Thanks for pointing that out. Updating hackage was previously one of my release checklist items. I don't handle the releases any more. Perhaps hackage provides a way to grant upload access to more than one person. Ideally a few of us should have this capability.

**Comment by uskudnik** [comment]
Thanks for quick reply! :) Yup, agreed on multiple person access (bus factor if nothing else :slightly_smiling_face: ).

I'm not very familiar with hackage (just haskell experiments under my belt for now) but per [upload doc](http://hackage.haskell.org/upload) it seems it might be possible:

````
If you upload a package or package candidate and no other versions exist in the package database, you become part of the maintainer group for that package, and you can add other maintainers if you wish. If a maintainer group exists for a package, only its members can upload new versions of that package.
````

**Comment by steve-chavez** [comment]
My bad, somehow thought this was included in our automated release script.

Seeing this in the hackage docs:
**You can only upload a package version once and this cannot be undone, so try to get it right the first time!**

Makes me think that'll be better to have the posgrest-bot as the only responsible for doing this. Seems we're only missing a `stack upload` in our script.

I'll make sure to add this step for the next release.

**Comment by steve-chavez** [comment]
Uploaded 0.5.0.0 to hackage but generating the docs failed because it tries to build with ghc-8.4.3(latest) http://hackage.haskell.org/package/postgrest-0.5.0.0/reports/3.

It's possible to re-upload the docs manually but the solution I've [seen](https://github.com/commercialhaskell/stack/issues/737) involves generating the docs with plain `cabal`, which I can't get to work with postgrest(we use stack).

For the next release, I'll restrict the [base package](https://wiki.haskell.org/Base_package) which limits the ghc version, hopefully hackage will pick this hint(anyone knows that?) and will build the docs correctly.

**Comment by steve-chavez** [comment]
Managed to make the docs build with just cabal. 

Also was told([comment](https://github.com/haskell/hackage-server/issues/559)) that the hackage server doc builder only works with ghc 8.4.3. 

There are issues when trying to run postgrest on that version(for example the `critbit` dependency doesn't compile), so I'm going to have to upload the docs manually until we can upgrade to ghc 8.4.3.

**Comment by steve-chavez** [comment]
Updated docs for 0.5.0.0 already up in http://hackage.haskell.org/package/postgrest-0.5.0.0.
