### ISSUE TITLE
How to manage a project source code?

### ISSUE THREAD

**Issue by itaied246** [PostgREST/postgrest#1193]
I have just started reading about this project and it seems very interesting.
Reading the docs, I can relate to a lot from the motivation and I like the idea.

I am still missing a guide or guidelines on how to manage a project.
Where do I store all of the SQL scripts?
How do I store them and in which structure?
What are the best practices for this?
Recommended migration tools?

**Comment by joonas-fi** [comment]
@steve-chavez that looks like a good one (though I don't know anything about postgrest - literally just arrived here)

Whatever the canonical example project would be, it'd be great if it was linked to from the readme.

**Comment by itaied246** [comment]
@steve-chavez How do you manage `sqitch` and the folder structure?
I have just installed `sqitch` and when I try to deploy migrations from other subfolder, it just doesn't find them.

**Comment by steve-chavez** [comment]
@itaied246  Sqitch creates some required files plus the dir structure(when doing `sqitch init`) in a particular folder and you need to be at that dir level for sqitch commands to work. Here's an example with the usual folder structure https://github.com/begriffs/postgrest-example, you could have that inside a `migrations` folder.

Definitely recommend checking the official tutorial first https://metacpan.org/pod/sqitchtutorial#Starting-a-New-Project

**Comment by itaied246** [comment]
How does the sqitch folder structure work together with postgrest?
`sqitch` require all the scripts to just be placed inside those 3 folders,
no sub-folders and no other structure.

Where should I look to read the state of a table?
The constraints inside it?
Functions defined on it?

**Comment by steve-chavez** [comment]
@itaied246 With PostgREST we try to follow a more declarative way of constructing your db schema, instead of just dumping DDL commands(CREATEs) into psql we create .sql files and then run a single `init.sql` that brings up the whole schema. This is also convenient for development since you can reproduce the schema easily(drop -> create) and also version control it.  

So, for consulting the tables/constraints/functions you only look at the .sql files instead of consulting pg metadata or doing psql slash commands(`\dt+`, `\df+`, etc)

About migrations folder structure, here's an example including them in the postgrest-starter-kit https://github.com/steve-chavez/postgrest-starter-kit/tree/ubuntu-tuto/db, these are autogenerated from the .sql files with [subzero-cli](https://github.com/subzerocloud/subzero-cli), you can see a tutorial for that here https://docs.subzero.cloud/managing-migrations/ (I think it had some problems with pg10, try to use a prior version).

**Comment by steve-chavez** [comment]
Moving the issue to postgrest-docs https://github.com/PostgREST/postgrest-docs/issues/222.
