### ISSUE TITLE
Feature Request: ability to call pg 11 stored procedure

### ISSUE THREAD

**Issue by sunbing81** [PostgREST/postgrest#1210]
### Environment

* PostgreSQL version: 11
* PostgREST version: 0.5.1
* Operating system: not relevant

### Description of issue

1. create the stored procedure (not a function)
```
create procedure api.test_proc(a int) language sql as $$
select 1;
$$;
```

2. make the request
```
POST /api/rpc/test_proc
Content-Type: application/json

{"a": 1}
```

3. postgrest cannot call a stored procedure for now
```
: HTTP/1.1 400 Bad Request
: Server: nginx/1.10.3 (Ubuntu)
: Date: Sat, 10 Nov 2018 09:04:34 GMT
: Content-Type: application/json; charset=utf-8
: Transfer-Encoding: chunked
: Connection: keep-alive
:
: {"hint":"To call a procedure, use CALL.","details":null,"code":"42809","message":"api.test_proc(a => integer) is a procedure"}
```

**Comment by steve-chavez** [comment]
At first I thought PROCEDUREs can't have return values, but turns out they work with INOUT parameters(only OUT parameters don't work btw).
```sql
create procedure public.test_proc(inout a int, inout b int) language sql as $$
select 1, 2;
$$;
 
call test_proc(3, 4);

 a | b 
---+---
 1 | 2
(1 row)
```

Going to have to think this through. Had the idea that a 204 No Content would always be the response.

**Comment by steve-chavez** [comment]
`call` syntax is severely limited. We cannot dynamically construct the input(arguments) and output(result) in SQL as we have done with traditional stored functions.

## Arguments

Not possible to:
```sql
-- use ctes
with smth as(
  select 1
)
call test_proc(3, 4);
-- ERROR:  42601: syntax error at or near "call"

-- use subqueries
call test_proc((select 3), (select 4));
-- ERROR:  0A000: cannot use subquery in CALL argument

-- it's possible to call functions in arguments though
create table myrowtype(a int, b int);
call test_proc((json_populate_record(null::myrowtype, '{"a":1,"b":2}')).a,(json_populate_record(null::myrowtype, '{"a":1,"b":2}')).b);
 a | b
---+---
 1 | 2

-- but not possible to use "AS" inside call
call test_proc((json_to_record('{"a":1,"b": 3}') as x(a int, b int)).a, (json_to_record('{"a":1,"b": 3}') as x(a int, b int)).b);
-- ERROR:  42601: syntax error at or near "as"
```
## Result

Not possible to:

```sql
-- wrap call inside a function
select row_to_json((call test_proc(3, 4)));
-- ERROR:  42601: syntax error at or near "test_proc"

-- use ctes for storing call results
with smth as(
  call test_proc(3, 4)
)
select * from smth;
```

## Proposal

For the **arguments** it's possible to do smth like:

```sql
call test_proc(a:= ('{"a":1,"b": 3}'::json->>'a')::int, b:= ('{"a":1,"b": 3}'::json->>'b')::int);
```
Downside is that the json must be copied. We could also do the conversion to json in haskell. Overall I think the **arguments** part is solvable.

For the **result**, we'd have to get all the stored procs inout parameters in the schema cache, decode dynamically(not sure if possible) and convert to json in haskell. For now, I'm inclining to **not return anything but the status codes** since INOUT is already limiting.

**Comment by steve-chavez** [comment]
One more limitation for stored procedures:

**If CALL is executed in a transaction block, then the called procedure cannot execute transaction control statements. Transaction control statements are only allowed if CALL is executed in its own transaction.**

From https://www.postgresql.org/docs/11/sql-call.html

That means we cannot use our regular transaction wraparound for stored procedures. If we use transaction wraparound then the stored proc can't have COMMITs/ROLLBACKs inside(useless basically).

**Comment by steve-chavez** [comment]
That means if we allow calling pg11 stored procedures we could not do our usual ROLE switching nor enforcing the `search_path`.

It breaks too much of our foundation to be worth adding for now.
If new PostgreSQL versions improve the situation we could reconsider.

**Comment by steve-chavez** [comment]
I made a draft implementation at https://github.com/steve-chavez/postgrest/tree/pg11-proc.
If COMMIT/ROLLBACK is used inside the stored procs then the following error is shown:
```json
{
    "code": "2D000",
    "details": null,
    "hint": null,
    "message": "invalid transaction termination"
}
```

**Comment by W1M0R** [comment]
@steve-chavez There can be a few reasons for the `invalid transaction termination` error. First of all, for `commit/rollback` to work, the root routine that calls the procedure, must be a procedure itself. If, let's say, there is a `runUserFunction` that itself is made with `create function` and it does `call user_routine`, then `user_routine` will fail if it is a procedure and it does a commit.

Other reasons for that error, could be when the called procedure has `security definer` in its signature, or uses a set clause.

**Comment by steve-chavez** [comment]
@W1M0R The main issue is that procedures can't do nested transactions. See https://dba.stackexchange.com/a/249453/158470.

Until that issue is solved in pg, stored procedures cannot be supported in postgrest(for the above reasons).

**Comment by W1M0R** [comment]
@steve-chavez Don't procedures just do nested transactions differently, i.e. instead of begin/end, they just `call` other procedures. 

From: https://www.postgresql.org/docs/12/plpgsql-transactions.html

>  A new transaction is started automatically after a transaction is ended using these commands, so there is no separate START TRANSACTION command. (Note that BEGIN and END have different meanings in PL/pgSQL.)

**Comment by steve-chavez** [comment]
@W1M0R To put it concisely, if this can be made to work:

```sql
BEGIN;
SET LOCAL search_path;
SET LOCAL role = 'anon';
CALL test_proc(3, 4); --  proc that uses transactions inside(has COMMIT)
COMMIT;
```
Then postgrest could support calling procedures.

**Comment by W1M0R** [comment]
Here is a message dated 2019-08-26 that confirms what you are saying, i.e. that this is indeed a current restriction of Postgres: https://www.postgresql.org/message-id/flat/99b87249-d08c-8082-340e-84273150b59e%402ndquadrant.com#74880e948075c03e3e209a60dd33af06

The problem lies in having to wrap the procedure call inside the transaction. Forgive my lack of understanding, but is it not possible to have the code base detect a procedure, and then call it outside the transaction, i.e. avoid a custom transaction all together and ensure that the procedure is called as the root?

**Comment by steve-chavez** [comment]
> Forgive my lack of understanding, but is it not possible to have the code base detect a procedure, and then call it outside the transaction, i.e. avoid a custom transaction all together and ensure that the procedure is called as the root?

Yes, but the problem is that we need to ensure the `SET LOCAL ROLE anon` is done. This is integral to postgrest auth: http://postgrest.org/en/v7.0.0/auth.html#authentication-sequence.

Besides from that, all of our HTTP logic wouldn't work too: http://postgrest.org/en/v7.0.0/api.html#http-logic. Those features relies on a bunch of SET LOCALs.

We cannot ensure the user created procedure would do that.

**Comment by W1M0R** [comment]
Thanks for helping me understand the broader issues of the problem @steve-chavez.

**Comment by wolfgangwalther** [comment]
> ```sql
> set role = 'anon'
> ```

Better to enforce the authenticator role here instead of anon. PostgREST could run without `db-anon-role` at all. And since we'd expect the stored procedure to make a call to `SET ROLE` anyway, it should start with a clean authenticator role.

**Comment by wolframm** [comment]
Hi! I'm considering Graphile vs PostgREST. Calling procedures would be important to me. Is there an approximate ETA for this topic?

**Comment by steve-chavez** [comment]
The restrictions for pg 11 procedures should be:

- `authenticator` would need GRANT EXECUTE on the procedure. Makes sense as we're basically conceding PostgREST authentication flow and transaction settings to the user.

- `set role to 'authenticator'` must be enforced on the procedure. i.e. we'll only allow procedures defined as `create procedure ..  set role to 'authenticator'`.

- No SECURITY DEFINER procedures. Makes sense as with `security definer` we essentially do `create procedure .. set role to 'postgres/superuser_like'`, which conflicts with the previous restriction.

- Only callable with POST. There's no volatility(STABLE, IMMUTABLE) marker on procedures.

- No filters will be applied on procedures

- Since it's not really possible to apply transformations on inputs and outputs(as shown [above](https://github.com/PostgREST/postgrest/issues/1210#issuecomment-500529022)), we should only allow a json input and output for starters. Later on this could be extended to other types like text or bytea. This way the implementation is simpler and also will tie in later with custom media types as discussed on https://github.com/PostgREST/postgrest/pull/1582.

```sql
-- we would recognize "request.body" and "response.body" as input and output
CREATE PROCEDURE hello("request.body" json, inout "response.body" json default null)AS $$
BEGIN
  -- role switch
  select json_build_object('hello', "request.body"->'name') into "response.body";
END$$
LANGUAGE PLPGSQL
SET role = 'authenticator';

-- later on: GET /rpc/hello "Content-Type: text/plain" "Accept: text/plain"
-- CREATE PROCEDURE hello("request.body" text, inout "response.body" text default null)
-- after #1582, custom media types could be done as
-- CREATE PROCEDURE hello("request.body" bytea, inout "response.body" "application/custom-mime" default null)

call hello("request.body" := '{"name": "world"}');
    response.body
---------------------
 {"hello" : "world"}
```

  (`inout` is used in this example because for some reason `out` parameters are mandatory when using `CALL`)

- `"request.jwt.claims" json, "request.headers" json` can be used as parameters as mentioned [above](https://github.com/PostgREST/postgrest/issues/1210#issuecomment-1180721273).

- [response.headers](https://postgrest.org/en/stable/api.html#setting-response-headers) and [response.status](https://postgrest.org/en/stable/api.html#setting-response-status-code) can also be used. 

- No [execution plan](https://postgrest.org/en/stable/api.html#execution-plan) on procedures(since EXPLAIN ANALYZE doesn't work on them anyway)

**Comment by steve-chavez** [comment]
Controlling the isolation level inside procedures is a bit weird:

```sql
CREATE OR REPLACE PROCEDURE hello(inout "response.body" json default null)
LANGUAGE PLPGSQL AS $$
begin
  commit;
  set transaction isolation level repeatable read;
  select json_build_object('hello', 'world') into "response.body";
END$$;
```

The first `commit` must be done, otherwise pg will err. See https://dba.stackexchange.com/a/289339/158470 - btw, the `default_transaction_isolation` method mentioned in that SO link could also be used to set isolation level on functions, as mentioned on https://github.com/PostgREST/postgrest/issues/2468#issuecomment-1500764279.

**Comment by steve-chavez** [comment]
> [response.headers](https://postgrest.org/en/stable/api.html#setting-response-headers) and [response.status](https://postgrest.org/en/stable/api.html#setting-response-status-code) can also be used.

These might be a problem, since we would depend on the order of the parameters for decoding the response in Haskell(no way to change this with `CALL`). The safest way would be to have a custom type like:

```sql
CREATE TYPE rest_response as (body json, headers json, status text);

CREATE OR REPLACE PROCEDURE hello("request.body" json, OUT res rest_response)
```

But then we'd have the problem that the `json` body is inside the type, so custom media types couldn't be used later(unless we create a new wrapper type for each one, which would unwieldy).

So we would need an additional OUT parameter for `headers/status`, it can be a type or we could also group them both in a single JSON. I'll leave this part for a later enhancement.

**Comment by steve-chavez** [comment]
> authenticator would need GRANT EXECUTE on the procedure. Makes sense as we're basically conceding PostgREST authentication flow and transaction settings to the user.

The above one is bad. So I've been thinking about another way. How about if we just use session-level variables? Basically for every session that hits `/rpc/pg11_procedure`:

```sql
SET role TO <jwt_role>;
SET request.jwt.claims TO <claims>;
CALL myprocedure();
RESET ALL;
```

https://www.postgresql.org/docs/current/sql-reset.html

Using `current_setting("request.jwt.claims", true)` inside `myprocedure` works fine too.

If we always set the role at the start of the session, the `RESET ALL` might not be needeed.

**Comment by steve-chavez** [comment]
> SET role TO <jwt_role>;
> SET request.jwt.claims TO <claims>;

So far the above seems to work fine.

In an attempt to not limit the function signature to `res OUT json` I tried to transform the procedure output in SQL, by putting the CALL results into a session-level setting:

```sql
-- having
-- create or replace procedure test.mult_them(a int, b int, c int, res out int)
-- language plpgsql as $$
-- begin
--   select a*b*c into res;
-- end$$;

do $$
declare res int;
begin
  call test.add_them(1, 2, 3, res);
  perform set_config('response.body', res::text, false);
exception
  when others then
    reset all; -- ensure the session-level settings are reset
    raise; -- reraise the exception so the error is reported to the client
end $$;
```

But since the anonymous DO block starts a transaction, the procedure cannot use transaction control statements inside(fails with "invalid transaction termination").. defeating the original purpose.

> create or replace procedure test.hello("request.body" json, inout "response.body" json)

So it's not possible to transform the output in SQL and the above restriction on signature must remain.

I think transforming the procs params in SQL to JSON might be doable with a session-level setting but since the body can be big, storing that result in a session-level setting could be trouble.

I think this is still better as no `authenticator` privilege will be required for the procedure nor switching roles manually.

Will add some tests to make sure the session-level settings don't conflict with the transaction-level ones.

**Comment by steve-chavez** [comment]
> create or replace procedure test.hello("request.body" json, inout "response.body" json)
> So it's not possible to transform the output in SQL and the above restriction on signature must remain.

By restricting the proc signature, I'm sure we'll cause a lot of confusion for users - increasing support burden.

Also while experimenting with procedures, me and @laurenceisla found out that they don't support using SAVEPOINTs([ref](https://www.dbi-services.com/blog/an-introduction-into-server-side-programming-in-postgresql-3-pl-pgsql-procedures/)). 

Doing a ROLLBACK inside can be accomplished by doing RAISE on a function, as we have recommended for a long time now.

One thing that is unique about store procedures is setting the transaction isolation level, but this can be supported on functions with https://github.com/PostgREST/postgrest/pull/2755 (by setting `default_transaction_isolation`, the same way is done on procedures).

For now I'll stop working on this as functions seem to be a fine replacement.

**Comment by foxydevloper** [comment]
I agree that considering the trade-offs, procedure support doesn't seem like a good fit for postgrest. I was originally hoping for support since I had a procedure that doesn't return anything, but I only just realized functions can return void, and it gives a proper 204 no content response. There should definitely be an error message if you try calling a procedure with /rpc/ syntax though because for a long time I was very confused as to why my /rpc/ call to a procedure wasn't working, since all it said was "couldn't find in schema cache"

**Comment by steve-chavez** [comment]
@MyProxyPass Hm, do you think that only SQL stored procedures are able to execute writes? SQL functions can do those just fine.

(Though as you point out, maybe we need a clear example of that in the docs)
