### ISSUE TITLE
Resource embedding with view works with some tables but not others

### ISSUE THREAD

**Issue by matt-snider** [PostgREST/postgrest#1230]
### Environment

* PostgreSQL version: docker postgres:11 (4dcf1ba7e5e2)
* PostgREST version: docker postgrest/postgrest:v5.2.0 (643538cf996d)
* Operating system: Arch Linux 4.19.11

### Description of issue

There appears to be an issue with resource embedding when using foreign keys with views. @steve-chavez was [able to reproduce](https://github.com/PostgREST/postgrest/issues/1179#issuecomment-454878513) the issue.

Here is the schema and minimal dataset:
```sql
-- Schema
CREATE TABLE projects (
  project_id  serial  PRIMARY KEY,
  name varchar(150)
);

CREATE TABLE sites (
  site_id     serial  PRIMARY KEY,
  name varchar(150)
);

CREATE TABLE jobs (
  job_id      uuid    PRIMARY KEY,
  site_id     int     NOT NULL REFERENCES sites,
  project_id  int     NOT NULL REFERENCES projects
);

CREATE VIEW stats AS
  SELECT
    site_id,
    project_id,
    count(job_id) AS number_of_jobs
  FROM sites
  JOIN jobs USING (site_id)
  JOIN projects USING (project_id)
  GROUP BY (site_id, project_id);

-- Data 
INSERT INTO projects (project_id, name) 
VALUES (1, 'project x'), 
       (2, 'project y');

INSERT INTO sites (site_id, name) 
VALUES (1, 'site x'), 
       (2, 'site y');

INSERT INTO jobs (job_id, site_id, project_id) 
VALUES ('bc5d5362-b881-438f-b9f5-7417e08704ed', 1, 1),
       ('3bd52697-033b-4edd-8a28-46a9c04b7c1e', 1, 2);
```

When attempting to embed a `site` object, I seem to receive list of jobs instead:
```
GET /stats?select=*,sites:site_id(*)
[
    {
        "site_id": 1,
        "project_id": 1,
        "number_of_jobs": 1,
        "sites": [
            {
                "job_id": "bc5d5362-b881-438f-b9f5-7417e08704ed",
                "site_id": 1,
                "project_id": 1
            },
            {
                "job_id": "3bd52697-033b-4edd-8a28-46a9c04b7c1e",
                "site_id": 1,
                "project_id": 2
            }
        ]
    },
    ...
]
```

Oddly this works when embedding a `project` object. Also notice that the `projects` query doesn't require the alias. The `sites` query does not work without it (i.e. _Could not find foreign keys between these entities, No relation found between stats and sites_).
```
GET /stats?select=*,project(*)
[
    {
        "site_id": 1,
        "project_id": 1,
        "number_of_jobs": 1,
        "project": {
            "project_id": 1,
            "name": "project x"
        }
    },
    ...
]
```

**EDIT**: Tested it with a regular table, and yes (obviously in hindsight), it does only relate to views.

**Comment by steve-chavez** [comment]
Our allSynonyms SQL query that detects relationships in VIEWs says:
```
 table_schema | table_name | table_column_name | view_schema | view_name | view_colum_name 
--------------+------------+-------------------+-------------+-----------+-----------------
 public       | jobs       | project_id        | public      | stats     | project_id
 public       | sites      | site_id           | public      | stats     | site_id
``` 
So the `stats` relationship with `sites` is being detected correctly. The bug must be in the Haskell logic, we pick the first detected relationship so maybe that's why `jobs` are being embedded.

As an aside comment, when having complex relationships is hard to grok what combination of hints to try in the URL to make PostgREST do the correct embedding.

I think we should make the detection more helpful, returning `300 Muliple Choices`(idea from https://github.com/PostgREST/postgrest/issues/994#issuecomment-340090051) in case there's more than one possible way to do the embedding, and ask the user to disambiguate by providing a list of all possible combinations.

**Comment by matt-snider** [comment]
Thanks for the response @steve-chavez . I agree that a clear message indicating ambiguity would be great to have

**Comment by matt-snider** [comment]
Thanks for the response @steve-chavez . I agree that a clear message indicating ambiguity would be great to have

**Comment by wolfgangwalther** [comment]
I tested this with the current nightly. I fail to see a bug here, this seems to me more like a feature request.

The way the view is written, embedding sites is not possible, because the view has `site_id` as a column **from sites itself**.

To make the view more explicit, the definition is the same as:

```sql
CREATE VIEW stats AS
  SELECT
    sites.site_id,
    jobs.project_id,
    count(jobs.job_id) AS number_of_jobs
  FROM sites
  JOIN jobs USING (site_id)
  JOIN projects USING (project_id)
  GROUP BY (site_id, project_id);
```

Note the three aliases I added in the `SELECT` part. `site_id` is detected to have the base column `sites.site_id`. Embedding on this is of course only possible for tables that reference this column.

The view can also be simplified to:

```sql
CREATE VIEW stats2 AS
  SELECT site_id
  FROM sites
```

Both views will have exactly the same embedding options here. Querying this on the current nightly returns the disambiguation error like this:

```json
{
    "hint": "By following the 'details' key, disambiguate the request by changing the url to /origin?select=relationship(*) or /origin?select=target!relationship(*)",
    "details": [
        {
            "relationship": "jobs_site_id_fkey[site_id][site_id]",
            "origin": "public.stats",
            "cardinality": "o2m",
            "target": "public.jobs"
        },
        {
            "relationship": "public.jobs[jobs_site_id_fkey][jobs_project_id_fkey]",
            "origin": "public.stats",
            "cardinality": "m2m",
            "target": "public.projects"
        }
    ],
    "message": "More than one relationship was found for stats2 and site_id"
}
```

Basically `stats` is interpreted as a view of `sites`. Embedding `sites` on a request to `stats` is the same as embedding `sites` on a request to `sites`. So some kind of self-reference, but not a self-reference to the same table (with foreign key), but a self-reference to the same **row** (without foreign key).

We just don't support self-referencing like this yet. While I don't think it makes sense to support this for tables. It's not so clear for views, though. This is because, with only a very small change to the view definition, `sites` **is** now embeddable:

```sql
CREATE VIEW stats3 AS
  SELECT
    site_id,
    project_id,
    count(job_id) AS number_of_jobs
  FROM jobs
  JOIN sites USING (site_id)
  JOIN projects USING (project_id)
  GROUP BY (site_id, project_id);
```

I just changed the `jobs` and `sites` here, so `sites` is now joined to `jobs`. Now `jobs` is the base table for `site_id` and instead of `jobs` and `projects`, it's `sites` and `projects` that are embeddable now, but `jobs` is not anymore.

While this is technically sound, I understand that this might be confusing for the user. It's amplified with the `USING`, because it hides the fact where those columns really come from.

It would be a lot less confusing, if we allowed to join all 3 tables here. But there is a problem: If we do that, then **every** view that has ever been written, will get one more new embedding opportunity. This will break a lot of queries, because **every embedding query to a view needs a hint now**, even in the simplest of cases.

I just don't see us going that way. Other opinions, anyone?

I feel like we should document this properly, so that people know what to expect when writing and embedding views.

**Comment by steve-chavez** [comment]
@wolfgangwalther I think you nailed it. Changing the VIEW definition is the solution.

So to reiterate and reconfirm, this is the view that should be used:

```sql
CREATE VIEW stats3 AS
  SELECT
    site_id,
    project_id,
    count(job_id) AS number_of_jobs
  FROM jobs -- the FROM is changed
  JOIN sites USING (site_id)
  JOIN projects USING (project_id)
  GROUP BY (site_id, project_id);
```

And now we can clearly embed `sites`(really the main issue):

```http
GET /stats3?select=*,sites(*)

[
    {
        "number_of_jobs": 1,
        "project_id": 1,
        "site_id": 1,
        "sites": {
            "name": "site x",
            "site_id": 1
        }
    },
    {
        "number_of_jobs": 1,
        "project_id": 2,
        "site_id": 1,
        "sites": {
            "name": "site x",
            "site_id": 1
        }
    }
]
```

And also `projects`:

```http
GET /stats3?select=*,projects(*)

[
    {
        "number_of_jobs": 1,
        "project_id": 1,
        "projects": {
            "name": "project x",
            "project_id": 1
        },
        "site_id": 1
    },
    {
        "number_of_jobs": 1,
        "project_id": 2,
        "projects": {
            "name": "project y",
            "project_id": 2
        },
        "site_id": 1
    }
]
```

All of this without embed hints or by using the column as the target. Much clearer.

**Comment by steve-chavez** [comment]
> It would be a lot less confusing, if we allowed to join all 3 tables here.
> I just don't see us going that way. Other opinions, anyone?

Yeah, me neither. It will cause a lot of breakage and it's also complicated for us.

> I feel like we should document this properly, so that people know what to expect when writing and embedding views.

Agree. We need to document that the embeds are done against the base table of the VIEW(the one in the `FROM`).

**Comment by steve-chavez** [comment]
> It's actually not the FROM table, but the table that is used for the column reference.

@wolfgangwalther True, I've just tried that VIEW and it also works. I've opened https://github.com/PostgREST/postgrest-docs/issues/382 for documenting that behavior.

**Comment by steve-chavez** [comment]
I believe the UNION enhancement proposal has been superseded by https://github.com/PostgREST/postgrest/issues/2144. Will close this one and work on docs on https://github.com/PostgREST/postgrest-docs/issues/382
