### ISSUE TITLE
Banishing the STRICT from Guide and our functions

### ISSUE THREAD

**Issue by ppKrauss** [PostgREST/postgrest#1294]
### Environment

* PostgreSQL version: any
* PostgREST version: any
* Operating system: any

### Description of issue
There are a PostgreSQL bug, [described here](https://stackoverflow.com/questions/8455177/function-executes-faster-without-strict-modifier), that deteriorates performance  of  SQL functions declared STRICT. The better solution is to avoid (**not** to recommend [like in the guide](http://postgrest.org/en/v5.2/api.html#stored-procedures)) the STRICT declaration.

The expected behavior vs actual behavior: 2x or 100x slower, depends on context and volume of data processing by function.

Steps to reproduce: see examples in the link.

**Comment by Qu4tro** [comment]
I'm sorry, but I don't see the issue. Postges performance issue is due an inline limitation, but in the example mentioned, the function will always be called once for each request on that endpoint. I think the lack of inlining there, won't affect the performance significantly. 

I agree that it's worth thinking whatever to document this quirk, since there's a reliance on postgres functions for a number of features (i.e. computed columns).

Note: I haven't actually tried, but I guess benchmarking this case wouldn't be hard to get to the bottom of it.

**Comment by ppKrauss** [comment]
> (...)  I think the lack of inlining there, won't affect the performance significantly.

Sorry, is very significant, and the observed performance difference is due to that added STRICT modifier, it is easy to test... [More one example](https://stackoverflow.com/q/56119704/287948): you can benchmark with OpenStritMap data, reduced from some hours (!) to 3.5 seconds.

> Note: I haven't actually tried, but I guess benchmarking this case wouldn't be hard to get to the bottom of it.

Please test by your self with bigdata. 

The main argument is that the little PostgREST gains of performance, we loss when exposing microservice using a function with STRICT... And the solution is very very simple: remove the "STRICT" modifier.

**Comment by steve-chavez** [comment]
We can remove STRICT from the API reference, and also add a warning about using it.

I'll move the issue to https://github.com/PostgREST/postgrest-docs/issues/224.
