### ISSUE TITLE
RPC json argument misinterpreted as text

### ISSUE THREAD

**Issue by fusionbeam** [PostgREST/postgrest#1350]
### Environment

* PostgreSQL version: postgres:11 (docker)
* PostgREST version: postgrest/postgrest:v6.0.0
* Operating system: macOS

### Description of issue

RPC argument of type json is not recognised when in application/json requests.
Postgrest tries to find a function with the same name and argument as type text and fails.

Here is the function header:
```
CREATE FUNCTION suitcase.register_new(first_name text, last_name text, email text, pass text, 
    team_name text, team_role text, profile_details json)
    RETURNS json
```

Here is the curl request:
```
curl -d '{"first_name":"test","last_name":"aaa","l.com","team_name":"blog.io","team_role":"owner","profile_details":{"account_type":"self-signed"}}' -H "Content-Type: application/json" -X POST http://localhost:8030/rpc/register_new -v
```

And here is the error message:
```
{"hint":"No function matches the given name and argument types. You might need to add explicit type casts.","details":null,"code":"42883","message":"function suitcase.register_new(email => text, first_name => text, last_name => text, pass => text, profile_details => text, team_name => text, team_role => text) does not exist"}
```

As you can see, the argument profile_details is identified as text instead of json.

Thanks,
R

**Comment by steve-chavez** [comment]
Try restarting postgrest, by default it assumes text if the schema cache is not updated.

**Comment by fusionbeam** [comment]
thank you. it's restarted, the container has been fully rebuild several times, same behaviour.

**Comment by sidh01** [comment]
I am also facing same kind of issue after I upgrade Postgrest from 5.2 to 6.0
The errror is argument user_id is identified as text instead of uuid.
 
 below is my function 
 CREATE FUNCTION  x.get_user_email_confirm_token(user_id uuid)  RETURNS json
 
 Here is the curl request:

curl -d '{"user_id":"64e53638-4ff1-4649-90c0-6a3e61c008c5"}' -H "Content-Type: application/json" -X POST http://localhost:8030/rpc/get_user_email_confirm_token -v

 Error:{"hint":"No function matches the given name and argument types. You might need to add explicit type casts.","details":null,"code":"42883","message":"function x.get_user_email_confirm_token(user_id => text) does not exist"}

**Comment by fusionbeam** [comment]
you were actually right.
although the openAPI endpoint was showing the correct parameters, it wasn't refreshed in Postgrest.

**Comment by steve-chavez** [comment]
Can confirm a schema cache refresh solves the problem, will add a note about this on the docs.

**Comment by patleb** [comment]
I'm getting the same issue with the official docker container on version 6.0.2 and  neither kill -s USR1 $(pgrep postgrest) nor restart works.

**Comment by xero88** [comment]
Did you solve your issue @sidh01 ? I have the same

**Comment by sidh01** [comment]
I just rebuild my postgrest whenever I have this issue
