### ISSUE TITLE
Allow requesting an empty body

### ISSUE THREAD

**Issue by Lindenk** [PostgREST/postgrest#1387]
Currently with every response an estimated (or exact if requested) count of records is returned along with the data. For large datasets, it might be helpful to have an option to return only the headers with an empty body. Although this doesn't necessarily reduce the time complexity of the query, it does save on bandwidth. I realize this can also be done with a view or stored procedure, but in most cases that's extra boilerplate for an already available bit of information.

I would imagine an empty body could be requested using a `Content-Type: none` header.

**Comment by steve-chavez** [comment]
@Lindenk That corresponds exactly to an HTTP [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) request. 

Support for that was added in https://github.com/PostgREST/postgrest/pull/1383.

**Comment by steve-chavez** [comment]
I've changed the count examples to use HEAD in the latest docs http://postgrest.org/en/latest/api.html#exact-count.

Also as you mention the SQL query will still be executed. For the case of HEAD `count=planned`, it seems we could avoid executing the query(since we only need an `EXPLAIN {query}`) but we use the query to construct other headers. In the future we could also add a way(using the query) to get the real body size through `Content-Length`(useful for HEAD), so it's probably not worth it to try avoiding executing the query.

I'll close since this is already implemented. You can [build from source](http://postgrest.org/en/latest/install.html#build-source) if you'd like to try HEAD now.
