### ISSUE TITLE
Follow odata v4 specifications?

### ISSUE THREAD

**Issue by FGRibreau** [PostgREST/postgrest#1398]
We might want to follow that in postgrest for pagination, field expansion, field selection etc... https://www.odata.org/documentation/

- pagination is done through $top & $skip https://docs.oasis-open.org/odata/odata/v4.01/csprd06/part2-url-conventions/odata-v4.01-csprd06-part2-url-conventions.html#_Toc21425354
- operators on strings are standardized https://docs.oasis-open.org/odata/odata/v4.01/csprd06/part2-url-conventions/odata-v4.01-csprd06-part2-url-conventions.html#_Toc21425292
- etc..

Just posting it here because I did not see any discussion around it :)

**Comment by steve-chavez** [comment]
What would be the advantages of adopting those specifications?

**Comment by FGRibreau** [comment]
Instead of postgrest own way of declaring filter operators and pagination we can rely on a standardized way of doing things. Thus promoting standard instead of doing/maintaining our own. 

![](https://imgs.xkcd.com/comics/standards.png)

**Comment by steve-chavez** [comment]
I had a glimpse of that spec. It uses url unsafe characters(the query string contains slashes and lots of spaces) which implies not being url friendly and needing to urlencode to share. The usage of `$` makes the url harder to read too. Overall that spec doesn't look like an improvement to what we have.

Also I don't think of it as a standard — since that would imply it's normally used/accepted — because I haven't seen any API in the wild following that spec(unlike, say, graphql apis).

Now, we do follow several standards. For example, for pagination, we follow [RFC 7233](https://tools.ietf.org/html/rfc7233). The query string syntax does follow our own way.

Instead of being caught up in the [Fire and Motion](https://www.joelonsoftware.com/2002/01/06/fire-and-motion/) of trying to comply with other specs, what I think we should do is to properly document our query string syntax(some advances in https://github.com/PostgREST/postgrest-docs/issues/228) and do a draft spec in our docs.

I say this(and think it's worth doing) because PostgREST has influenced REST implementations([blockapps API](https://developers.blockapps.net/advanced/concepts/#cirrus)) and possibly other specs.

That would be much more easier to do and maintain for us.

**Comment by ako** [comment]
Benefit of odata is that there are a number of useful tools that already have odata support built in.

OData is used heavily by SAP and Microsoft to expose data. On the consuming side you have tools like PowerBI, Excel, Tableau, Lyncpad, Microsoft SSIS (ETL) that can directly read odata. Odata provides users the option to do analytics on data where the database is not directly available.

**Comment by steve-chavez** [comment]
Realistically speaking, if compatibility with another spec is desired, the best way to do it would be translating the request at the proxy layer. In a simillar manner to what [ppKrauss/PostgREST-writeAPI](https://github.com/ppKrauss/PostgREST-writeAPI) does.

Also, I can see the advantages for orgs that heavily use an MS/SAP stack. But at the same time, those orgs are in the conditions to pay :moneybag: for commercial software. Perhaps this would be a feature more fit for [subzero.cloud](https://subzero.cloud/).

**Comment by wolfgangwalther** [comment]
It seems like the result of this discussion is the goal to better document the existing query string syntax. https://github.com/PostgREST/postgrest-docs/issues/228 is still open for that, so I am closing this here.

**Comment by shayneoneill** [comment]
Was this going to be a wont-do ? Theres an integration I have that needs odata but the closest to a solution I've found is one of those awful random cloud offerings where they wont even tell you a price unless you talk to a salesman (Thats an instant "NOPE" from me. hidden prices means something to hide.)

**Comment by steve-chavez** [comment]
> Theres an integration I have that needs odata but the closest to a solution I've found is one of those awful random cloud offerings where they wont even tell you a price unless you talk to a salesman

Yeah, I see those too. No true OSS alternative. Also now some products offer OData integrations.

Nowadays we have better separation of concerns in our codebase. We have ASTs for the different operations:

https://github.com/PostgREST/postgrest/blob/60fe59c3fb1e62eefc0262ed661acaf3ce381647/src/PostgREST/Plan/ReadPlan.hs#L30-L48

https://github.com/PostgREST/postgrest/blob/60fe59c3fb1e62eefc0262ed661acaf3ce381647/src/PostgREST/Plan/MutatePlan.hs#L19-L46

And the query string parsing is done on

https://github.com/PostgREST/postgrest/blob/60fe59c3fb1e62eefc0262ed661acaf3ce381647/src/PostgREST/ApiRequest.hs#L143

In theory we could have an external Haskell library that translates the query string into that AST.

Likely I miss some details, but overall it seems more feasible now.

**Comment by steve-chavez** [comment]
@HoldYourWaffle That sounds great! Currently we do the query param parsing in https://github.com/PostgREST/postgrest/blob/c4ef9c09954a7695e215f18285c150fa13e41614/src/PostgREST/ApiRequest/QueryParams.hs. There's no separate library yet, but if you'd like to take a stab at this for now you could create another module. I assume we would also need a config since Odata and PostgREST query grammar could clash.
