### ISSUE TITLE
Change misleading config options names

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#1413]
These config options often cause confusion among users:

- [server-proxy-uri](http://postgrest.org/en/v6.0/configuration.html#server-proxy-uri): the name doesn't imply it's related to the openapi output and misleads into thinking it's a web server setting. It'd be better to change it to `openapi-server-proxy-uri`.

- [db-extra-search-path](http://postgrest.org/en/v6.0/configuration.html#db-extra-search-path)(name was discussed in https://github.com/PostgREST/postgrest/issues/1200): this always seems related to exposing more than one schema. Since the original intent was only to make it easier to work with extensions, I suggest renaming it to `db-extensions-schema`. Default still would be public and it'll keep accepting a schema list.

**Comment by ruslantalpa** [comment]
first is better, second is worse
the "confusion" comes from two categories:
- ppl that are new to postgresql and do not know that a searchpath is for
- ppl who know that it is and think they can "hack" a solution to expose different schemas (and on top do not read the manual)

I think the second should stay as it is since it exactly describes what it does, the name is good and the docs are good, all ppl have to do is read them to know this can not be used to expose more schemas.

**Comment by steve-chavez** [comment]
`db-extra-search-path` is misleading because is not a one to one mapping of the pg feature to the pgrst feature.

- users that know search_path, expect it to be the way to expose schemas.
- users that don't know search_path, could look for search path official docs(instead of our docs) and then also think it's for exposing schemas.

Adding an extra search path is what we do but it's not the intent of the config, the intention is to make extensions work normally.

I only see disadvantages if we keep that name, it only creates more support burden. Also, the breaking change should have minimal impact since the default `public` works fine for most users.
