### ISSUE TITLE
Handling dropped HTTP requests

### ISSUE THREAD

**Issue by savv** [PostgREST/postgrest#1424]
### Environment

* PostgreSQL version:  PostgreSQL 12.1
* PostgREST version: 6.0.2
* Operating system: OSX

### Description of issue
Background:
Our mobile app operates in an environment with low connectivity. In order to prevent double inserts, the client needs to know for sure whether an insert succeeded or not, so it can decide whether to retry.
Unfortunately, it seems that when a request is dropped mid-flight, the transaction is not cancelled. One alternative in this simple case is to use UUIDs (assigned by the client). Regardless, this seems worth fixing.

Steps to reproduce:

1. Follow the steps in tutorial 0 and tutorial 1 (I granted permissions to web_anon to simplify).
2. Simple insert via HTTP to verify it works: `curl http://localhost:3000/todos -X POST -H "Content-Type: application/json" -d '{"task": "learn how to auth"}'`
3. Verify addition via `curl http://localhost:3000/todos`
4. Now re-run (2), but force it to fail:
```
$ curl http://localhost:3000/todos -X POST -H "Content-Type: application/json" -d '{"task": "learn how to handle HTTP :)"}' --limit-rate 1 --max-time 0.1
curl: (28) Operation timed out after 102 milliseconds with 0 bytes received
```
_Notice "Operation timed out"_

5. Verify it was added to DB (even though it shouldn't):
```
$ curl http://localhost:3000/todos
[{"id":1,"done":false,"task":"finish tutorial 0","due":null},
 {"id":2,"done":false,"task":"pat self on back","due":null},
 {"id":3,"done":false,"task":"learn how to auth","due":null},
 {"id":4,"done":false,"task":"learn how to handle HTTP :)","due":null}]
```

**Comment by steve-chavez** [comment]
How can this be done server-side in theory? A timeout for a FIN packet from the client and then rollback the transaction? I'm not really sure..

Do you know of any other server implementation that handles this kind of case?

**Comment by wolfgangwalther** [comment]
> Our mobile app operates in an environment with low connectivity. In order to prevent double inserts, the client needs to know for sure whether an insert succeeded or not, so it can decide whether to retry.

What you are asking for is an atomic transaction extended to the client-side. Only if the client confirms the response, should the transaction actually be committed, otherwise rolled back. We can not do that.

Even if you were to be able to handle a dropped http request and cancel the transaction, there would still be race conditions where you can't be a 100% sure:

- Assuming the order of things on the postgrest side is `COMMIT`, then send response to client: What if commit succeeded, but before the response is fully sent, the connection drops?

- Assuming the order of things postgrest side is send response, then `COMMIT`: What if you get the response and just before the postgrest can commit the server crashes? Not even mentioning deferred constraints, that might only trigger on commit.

In theory it is possible to guarantee atomic transactions - but not useful here with low connectivity. The REST way to solve this, is by providing idempotency. In your case, you need to make sure that the request is repeatable without creating duplicates. So yes, using a UUID, in absence of a natural pk, seems the best way to.

On a different note: I would not want PostgREST to drop a bit of a longer transaction just because of connection problems in a mobile environment. This could make it hard to ever get the request through.

Given the conceptual and implementation challenges of this (or just "even if we want to, how are we going to do this?"), I'm closing this for now. Feel free to re-open if any of those can be met.
