### ISSUE TITLE
New release v6.0.3 ?

### ISSUE THREAD

**Issue by aadrian** [PostgREST/postgrest#1459]
Hi,

Any chance getting a new official release? e.g. v6.0.3?

Thank you.

**Comment by steve-chavez** [comment]
`v7.0` will be released once #1450 is merged. Work there got interrupted because a non-minor bug had to be fixed in https://github.com/PostgREST/postgrest/pull/1458. But we should finish #1450 around next week.

For now you can [build from source](http://postgrest.org/en/latest/install.html#build-source) to get the [latest features](http://postgrest.org/en/latest/releases/upcoming.html).
