### ISSUE TITLE
VARIADIC (Functions with variable numbers of arguments) is not supported with any array type

### ISSUE THREAD

**Issue by towcy** [PostgREST/postgrest#1470]
### Environment

* PostgreSQL version: 11
* PostgREST version: 6.0.2
* Operating system: Ubuntu 18.0.4

### Description of issue
URL: http://127.0.0.1:3000/rpc/test?col1=val1&col2=val2
Error Details: You might need to add explicit type casts.","details":null,"code":"42883","message":"function public.callback(col1 => text, col2 => text) does not exist"}
Function Header: CREATE OR REPLACE FUNCTION public.test(VARIADIC data text[])

**Comment by steve-chavez** [comment]
Yes, that way of calling the function is not supported. Mostly because we only support calling the function through named parameters. You cannot call the variadic in pg like:

```sql
-- with this variadic
create function test.my_variadic(variadic data int[]) returns int[] as $$ select data $$ language sql;

-- this doesn't work
select test(col1 := 3, col2 := 4);

-- You can call it like
select my_variadic(3, 4);
-- or
select my_variadic(variadic '{3,4}');
```

So, we should support calling the variadic like:
```bash
curl "http:/localhost:3000/rpc/my_variadic?data=\{3,4\}"
## or
curl 'http:/localhost:3000/rpc/my_arr?data=%7B3,4%7D'
```
But that's not working for a variadic somehow.

You can make it work for a regular array input though:
```sql
create function test.my_arr(data int[]) returns int[] as $$ select data $$ language sql;
```

```http
curl "http:/localhost:3000/rpc/my_variadic?data=%73,4%7D"
[3, 4]
```

Be sure to reload the schema cache when trying that.

**Comment by wolfgangwalther** [comment]
Calling a function with variadic argument is also possible with named args like this:

```SQL
select my_variadic(variadic data := '{3,4}');
```

So, the only thing to do to support variadic would be to add the `variadic` to the query?

I wonder whether it would be possible to support something like this:

```shell
curl "http:/localhost:3000/rpc/my_variadic?data=3&data=4"
# and
curl "http:/localhost:3000/rpc/my_arr?data=3&data=4"
```
->
```SQL
SELECT my_variadic(variadic data := '{3,4}');
-- and
SELECT my_arr(data := '{3,4}');
```

So just creating an array out of multiple query parameters with the same name. That would be independent of whether it was a regular array or a variadic argument.

**Comment by steve-chavez** [comment]
> select my_variadic(variadic data := '{3,4}');

@wolfgangwalther I didn't know about that one, that's cool. With that we can support variadic functions following the same rules as pg. e.g. a function like `my_variadic(label text, variadic data int[])` could be called as usual: `/rpc/myvariadic?label=lebal&data=%73,4%7D`

> So, the only thing to do to support variadic would be to add the variadic to the query?

Yes, it seems that would do. We'd have to detect the variadic parameters in the schema cache.

> curl "http:/localhost:3000/rpc/my_variadic?data=3&data=4"
> So just creating an array out of multiple query parameters with the same name.

I think right now we get the first "data" and ignore the others. Seems possible in principle, but I'm not sure it would be worth it. Usually with variadic/arr you want to put more than a couple of values.

```bash
curl "http:/localhost:3000/rpc/my_variadic?data=%7B3,4,5,6,7,8%7D"
# vs
curl "http:/localhost:3000/rpc/my_variadic?data=3&data=4&data=5&data=6&data=7&data=8
```

In that case the latter url is a bit longer to type.

Still I think the variadic support would be good for compliance with pg.
On the docs, we could add it after [calling functions with array parameters](http://postgrest.org/en/v7.0.0/api.html#calling-functions-with-array-parameters) and also mention that it uses the array literal notation.

**Comment by wolfgangwalther** [comment]
> I think right now we get the first "data" and ignore the others. Seems possible in principle, but I'm not sure it would be worth it.

I probably I agree. I just noted that, because I asked myself why anyone would actually want to use a `VARIADIC` function instead of a function with regular array argument as an RPC. From the query perspective, both are exactly the same.

The only "reason" I can think of, where you would benefit from a query structure like this, would be a situation where you have a given URL to `/rpc/something?a=` and need to somehow manipulate (iee "add to") that URL on the fly (maybe in a proxy setting?). In this case, just appending `&a=value` as many times as I want to, would be a lot easier compared to breaking up that array and inserting `,value` in the right place. This is not a concrete example, I know, but made-up so far. So unless it's an easy thing to do and it has not yet been asked for, it's probably not worth it.
