### ISSUE TITLE
Feature Request: metrics or instrumentation

### ISSUE THREAD

**Issue by sevagh** [PostgREST/postgrest#1526]
It would be nice to have a `/metrics` endpoint that exposes Prometheus-style metrics.

Note that I might be opinionated for working mostly with the Prometheus ecosystem - perhaps a more general metrics library, with different exposition formats to choose from, could work? I also don't know which existing Haskell metrics libraries or Prometheus libraries exist or are good (but hackage shows there might be some).

I'm not sure what metrics are the best to expose. I bet PostgREST developers know more about essential PostgREST KPIs. But things like:

```
postgrest_query_execution_time (histogram)
postgrest_http_requests
postgrest_schema_reloads
...
```

**Comment by steve-chavez** [comment]
Needs more discussion, but It could be a good idea!

One thing I'd like to note for now is that we can't use a `metrics` endpoint because it would conflict with users routes(one example of using a `metrics` table [here](https://gitter.im/begriffs/postgrest?at=5f036594bb149531edf2ec74)). So maybe we can come up with a prefix, like `/pgrst/metrics` or `/internal/metrics`.

**Comment by sevagh** [comment]
That sounds good. Given PostgREST + NGINX is the recommended/common deployment, one could easily expose the internal metrics prefix at their desired location.

**Comment by steve-chavez** [comment]
On https://github.com/PostgREST/postgrest/issues/1933, we were thinking of using a special header for this and avoid creating an extra route.

Seems Prometheus doesn't support adding headers for scraping though :disappointed: https://github.com/prometheus/prometheus/issues/1724

> PostgREST + NGINX is the recommended/common deployment

But since Nginx would be present, then I guess it's not a problem because it can map the header to a url. Another option in the future might be https://github.com/PostgREST/postgrest/issues/1909 as well. So a special header would do.

**Comment by darora** [comment]
Hmm at least for liveness/health checks, we'd want to be hitting the postgrest instances directly, rather than going through nginx or a similar rewriting layer.

Even with an nginx setup, I'd imagine we generally have it load balancing between multiple postgrest instances transparently, so even for metrics you'd likely want to be hitting each instance directly, rather than going over nginx.

One alternative would be to use a secondary port to host endpoints for liveness/metrics etc. This would avoid creating a breaking change where we reserve e.g. `/internal` or a similar base path, and trivially allow users to not expose these endpoints externally.

**Comment by rupurt** [comment]
Can haskell run multiple web servers on different ports? That's how it's typically done in other languages so that you don't have route path conflicts + you typically don't expose the prometheus webserver port to the outside world.

**Comment by steve-chavez** [comment]
@rupurt Yeah, we already have that on latest  https://postgrest.org/en/latest/configuration.html#admin-server-port

**Comment by rupurt** [comment]
@steve-chavez awesome. Would be great to have prometheus metrics in there :smile:

**Comment by uhbif19** [comment]
Is it okay to use https://hackage.haskell.org/package/prometheus for this task?

**Comment by steve-chavez** [comment]
@uhbif19 Yes, that one should do.


For posterity, https://github.com/PostgREST/postgrest/pull/2129 was closed but the pool metrics discussed there would still be useful.

**Comment by bhupixb** [comment]
Has this feature been released in any 10.x version?

**Comment by steve-chavez** [comment]
Nope, not yet implemented.

(Issue would be closed if so)

**Comment by steve-chavez** [comment]
These days seems we should be using OpenTelemetry instead of Prometheus. Maybe with https://github.com/iand675/hs-opentelemetry.

Article about the differences: https://www.timescale.com/blog/prometheus-vs-opentelemetry-metrics-a-complete-guide/

**Comment by steve-chavez** [comment]
A metric for the connection pool max acquisition time would be helpful to prevent [acquisition timeouts](https://postgrest.org/en/stable/references/connection_pool.html#acquisition-timeout). While it gets higher it will reach the timeout.
