### ISSUE TITLE
Stored Procedure that gets a random value always returns the same after 5 consecutive API calls

### ISSUE THREAD

**Issue by jantari** [PostgREST/postgrest#1568]
### Environment

* PostgreSQL version: 12.2
* PostgREST version: PostgREST 7.0.1
* Operating system: Ubuntu Server 20.04.1 LTS

### Description of issue

A stored procedure that consistently gets a random value when run through `psql` keeps returning the exact same thing when called through PostgREST within a short timeframe.

**Expected behavior**

For the purpose of the demonstration I am using the `api.todos` table from the PostgREST tutorial with ~32k tasks inserted.

I have the following stored procedure in my DB:
```sql
CREATE FUNCTION api.getrandom()
RETURNS text AS $$
  SELECT LOWER(task) FROM api.todos ORDER BY RANDOM() LIMIT 1;
$$ LANGUAGE SQL IMMUTABLE;
```
I realize this isn't very efficient or truly truly super-random, but I only expect up to ~50k rows and somewhat-random is OK for my usecase. For the record though, the problem also happens with the following SP:
```sql
CREATE FUNCTION api.getrandom()
RETURNS text AS $$
  SELECT LOWER(task) FROM api.todos OFFSET floor(random()* (SELECT COUNT(*) FROM api.todos)) LIMIT 1;
$$ LANGUAGE SQL IMMUTABLE;
```

When calling this multiple times from the `psql` shell, it returns a nice spread of random-enough values:
```bash
for i in {1..40}; do psql -tAqX -d postgres -c "SELECT api.getrandom()"; done
```

so I know this isn't a problem with the SP not being random enough. However, when calling the SP through PostgREST:
```bash
for i in {1..40}; do curl -sq http://localhost:3000/rpc/getrandom -H 'Accept: text/plain';echo ""; done
```
I consistently get 5 different results at first and then 35 times the same result.
I tried looking through the documentation to find some caching mechanism but couldn't find anything.
Adding `-H 'Cache-Control: no-cache'` to `curl` doesn't make a difference either way.

**Comment by wolfgangwalther** [comment]
You have defined your function as `IMMUTABLE`. Citing the postgres docs (https://www.postgresql.org/docs/current/xfunc-volatility.html):

> An IMMUTABLE function cannot modify the database and is guaranteed to return the same results given the same arguments forever. This category allows the optimizer to pre-evaluate the function when a query calls it with constant arguments.

When you make your call through PostgREST, the same database connection / session is used for those calls. In this session, postgres has already cached the result for your function call and does not execute it again - because it's `IMMUTABLE`.

In your psql example, you create a new session every time and the result is not cached.

If you define your function as `STRICT` instead of `IMMUTABLE`, this should work with the PostgREST call as well:

> A STABLE function cannot modify the database and is guaranteed to return the same results given the same arguments for all rows within a single statement.

Note the difference between "within a single statement" for `STRICT` and "forever" for `IMMUTABLE`.

I would suggest to call this RPC with `POST` as well instead of `GET`. `GET` implies that the result is cachable and might return the same result for different calls as well, if you have any caching layers between your client and PostgREST.

**Comment by jantari** [comment]
Oh man, being a newbie to SQL I feared it would be my own fault but I just couldn't figure it out.

Thanks a lot for the detailed help, you are right it works as expected with `STABLE` (you mention `STRICT` a bunch of times, I assume it's a typo?)

**Comment by wolfgangwalther** [comment]
Absolutely, I meant `STABLE` instead of `STRICT` - confused myself here a bit :)
