### ISSUE TITLE
Row level security: no warning when delete is prevented

### ISSUE THREAD

**Issue by tad-lispy** [PostgREST/postgrest#1574]
### Environment

* PostgreSQL version: Docker, `postgres:12.4`
* PostgREST version: Docker, `postgrest/postgrest:v7.0.1`
* Operating system: OS X 10.14.6

### Description of issue

I'm trying to apply row level security to a delete operation. Here is my policy (crafted to always fail to demonstrate the problem):

```sql
Create policy allow_collections_delete
on private.collections
for delete
to api
using (false);
```

This results in `DELETE /collections` taking no effect. It gives `204` status as if the rows were deleted, but they are still there:

```
$ http DELETE :3000/collections \
	"Authorization: Bearer [...]" \
	"name=test-collection" \

HTTP/1.1 204 No Content
Content-Range: */*
Date: Wed, 19 Aug 2020 09:45:16 GMT
Server: postgrest/7.0.1 (UNKNOWN)

$ http GET :3000/collections \
	"Authorization: Bearer [...]" \

HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Location: /collections
Content-Range: 0-0/*
Content-Type: application/json; charset=utf-8
Date: Wed, 19 Aug 2020 09:57:53 GMT
Server: postgrest/7.0.1 (UNKNOWN)
Transfer-Encoding: chunked

[
    {
        "id": "d39ff079-a6c7-456f-8ec8-ceaecaeacd2e",
        "name": "test-collection",
        "owner": "34620634-ec55-4547-84ce-814801846f7d",
        "title": "Test Collection"
    }
]
```

I would expect something like `403` with a message along the lines of: `operation violates row-level security policy for table "collections"`.

The `api` user is the owner of all the views in the `api` schema and has all required privileges to tables is the`private` schema. If I change the `using` clause to correct expression (or simply `true`) the rows are deleted as expected.

I'm not sure if it's about the docs, PostgREST itself or maybe I'm doing something wrong. Please advise.

**Comment by wolfgangwalther** [comment]
You seem to be aware of the "security definer" aspect of `VIEW`s, because you mentioned the `api` user as the owner etc. - also the fact that the `DELETE` takes no effect, means the RLS is not by-passed.

I assume `api.collections` is auto-updateable and you have no custom rules or triggers in place.

The request you are making boils down to `DELETE FROM private.collections`. Conceptually (in a RLS sense) this means: Delete all the rows that I can see. The `USING` clause for this policy makes the delete statement see **no rows at all**. Trying to delete no rows, will not throw an error. That makes sense.

Citing the docs at https://www.postgresql.org/docs/current/sql-createpolicy.html:

> `using_expression`
> Any SQL conditional expression (returning boolean). The conditional expression cannot contain any aggregate or window functions. This expression will be added to queries that refer to the table if row level security is enabled. Rows for which the expression returns true will be visible. **Any rows for which the expression returns false or null will not be visible to the user** (in a SELECT), and will not be available for modification (in an UPDATE or DELETE). **Such rows are silently suppressed; no error is reported.**

And further down:

>`DELETE`
> Using DELETE for a policy means that it will apply to DELETE commands. **Only rows that pass this policy will be seen by a DELETE command.**

You will only get RLS errors if you have a difference between your `USING` and your `WITH CHECK` clauses, if I understand correctly. `WITH CHECK` is not used by `DELETE` at all. I don't think a `DELETE` will ever throw because of RLS.

**Comment by tad-lispy** [comment]
Thank you for your very clear explanation. I missed the relevant docs from Postgres 🤭

The conclusion I am making is to use an _instead of delete_ trigger for failure reporting and optionally RLS as a last line of defense.
