### ISSUE TITLE
The stale schema cache

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#1688]
Sometimes the schema cache is not up to date anymore. This can happen during startup, or after changes to the database schema.

PostgREST's current approach is to continue to serve requests on a best effort basis - this is most notably the case for RPCs. RPC functions can be overloaded and need to be identified properly to set the correct transaction isolation level, create the right embedding queries and return the result appropriately formatted. For RPCs the stale schema cache issue is further amplified because `findProc` also tries to find the right function on a best effort basis - both with and without up to date schema cache.

This leads to all kinds of hard to unterstand (for the user) and hard to debug (for developers) issues, like #1469, #1638 and #1672. Also our issue template tells quite a story about it:

```
Before reporting a bug:
If your database schema has changed while the PostgREST server is running,
send the server a SIGUSR1 signal or restart it(http://postgrest.org/en/stable/admin.html#schema-reloading)
to ensure the schema cache is not stale. This sometimes fixes apparent bugs.
```

I propose to get rid of the whole "best effort" approach and do the following:

1. **find exact matches for RPCs or error out**: `findProc` should find an exact match for the function arguments/types. If no match is found, it should throw an error. If multiple matches are found, it could return some kind of 300 response, similar to the "hey I don't know which embedding you want" message. To be able to tell functions with the same name but different argument types apart we could add "hints" in the form of "virtual casts" for the arguments. Assume we have a two functions with the same name and same argument name - but one them has the argument as int, the other one as text. We could make requests like this:

  ```
  GET /rpc/func?arg::int=123
  GET /rpc/func?arg::text=asd
  ```

2. **Make calls to RPCs 100% explicit.** No "unknown" type arguments. We cast them all exactly the way we expect the function to be according to our request and schema cache. This avoids any "whoops, we called the wrong function here" situations.

_(There was a part here about updating the schema cache automatically on failed requests. This is useless, because those requests would error out anyway. New database objects could not be detected by this, so we can as well skip it.)_

This can be extended to requests to tables. Fail early if unknown columns are requested - no need to hit the database with it, trust the schema cache.

If the schema cache is out of date, we might return errors for requests that could be served, because the a function or table has been added in the meantime. This is not a problem. Before the function is created, we will get an error. After the schema cache is updated we get no error. This approach just delays the ability to call the function until the schema cache is up to date. This should happen anyway.

Force people to update their schema cache. Everybody will quickly understand "table/function not found" errors after adding stuff. Plus, since this error will be thrown directly from haskell, we can add "please update your schema cache, if this function should exist, bla bla" to it.

**Comment by steve-chavez** [comment]
> find exact matches for RPCs or error out
> "please update your schema cache, if this function should exist, bla bla" to it.

@wolfgangwalther Yeah, I agree with that. I think it can be done. We can provide a good error message.

> GET /rpc/func?arg::int=123

Also sounds good good. So the user can disambiguate the function as well.

> Make calls to RPCs 100% explicit. No "unknown" type arguments. 

Do we use unknown for rpc args? IIRC, we type them explicitly(see `pgaType a`):

https://github.com/PostgREST/postgrest/blob/0c25f128250f427f470910104eea6b8bee589083/src/PostgREST/QueryBuilder.hs#L130

> This can be extended to requests to tables. Fail early if unknown columns are requested - no need to hit the database with it, trust the schema cache.

Not sure about that one. The pg error for unknown columns is pretty clear.

In general I see the schema cache as an aid for things that cannot be done dynamically(or need to be cached) in pg, not necessarily our source of truth(which is the db). We didn't need the schema cache for columns until now(don't remember an issue) because unknown casting on the filters works perfectly.

Also, consulting the schema cache for each column(and computed column) we get on filters or `select` would be costly I believe.

> no need to hit the database with it,

I also like the idea of not hitting the db when we can, but doing it for unknown columns seems a bit complex to me.

I think that for this case, we should be looking at caching https://github.com/PostgREST/postgrest/issues/1176.

> Force people to update their schema cache.

That reminds me that we need to finish the EVENT TRIGGER on https://github.com/PostgREST/postgrest/issues/1512#issuecomment-643687504. That one could also help with the wrong function called issue.

**Comment by wolfgangwalther** [comment]
> Do we use unknown for rpc args? IIRC, we type them explicitly(see `pgaType a`):

Maybe this is more related to the "default to text if argument not found" then. But this would be solved with the first point already, because "argument not found" would be an error.


> Not sure about that one. The pg error for unknown columns is pretty clear.

I'm not sure about it anymore, either. I think that somehow followed from the - meanwhile removed - idea of auto-refreshing the schema cache on a failure.


I think this all comes down to "**find exact matches for RPCs or error out**". If we do that, we should have the important stuff covered, I think.

**Comment by steve-chavez** [comment]
@wolfgangwalther Yeah, this is a sure enhancement if we limit it to the RPC case.

It will be a breaking change, but a good one I believe. Similar to the 300 error for embedding, as you mentioned.
