### ISSUE TITLE
Make `db-anon-role` optional

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#1689]
Came up in https://github.com/PostgREST/postgrest-docs/issues/381.

If we make `db-anon-role` optional, we can block any anonymous access when it is not set.

**Comment by wolfgangwalther** [comment]
Taken from #1823:

> we should print a warning when neither anonymous access nor JWT is set up

This would make the server pretty much disfunctional.

**Comment by steve-chavez** [comment]
Taken from https://github.com/PostgREST/postgrest/issues/2104#issuecomment-1001175822:

> I expected that if I set the jwt-secret parameter in the configuration, it would automatically set that only jwt-authorization would work.

I like the above, when the `jwt-secret` is set, force the JWT for all requests and basically disable `db-anon-role`. It's good for a quickstart because all users start with an empty `jwt-secret`. It kinda goes in line with our tutorials as well, tut0 main topic is the anonymous role and for tut1 is the  JWT secret.

Having `db-anon-role` by default is still a problem because it requires a proxy for disallowing public access, something we can do ourselves.

**Comment by wolfgangwalther** [comment]
> I like the above, when the `jwt-secret` is set, force the JWT for all requests and basically disable `db-anon-role`. It's good for a quickstart because all users start with an empty `jwt-secret`. It kinda goes in line with our tutorials as well, tut0 main topic is the anonymous role and for tut1 is the JWT secret.

I don't see how that's related to `jwt-secret`?

You can't disable anonymous requests, when `db-anon-role` is given - but you can't enable them either, when it's not (once that's possible).

A given `jwt-secret` will just enable **authenticated** requests. If it's not there, no authenticated requests are possible. But I don't see any interaction with `db-anon-role` / anonymous requests, other than https://github.com/PostgREST/postgrest/issues/1689#issuecomment-822251955.

**Comment by cemremengu** [comment]
Technically if anon role is not defined on db side no requests would be allowed so it is good.

But still I am thinking on the necessity of anon role. I am pretty sure a rest api for database will almost always need some kind of auth and believe it is a security issue to have an anon role.

Going with secure by default, instead of anon `basic authentication` should be provided as the default and then jwt could optionally be enabled.

**Comment by wolfgangwalther** [comment]
> Going with "secure by default" mantra, instead of anon `basic authentication` should be provided as the default and then jwt could optionally be enabled.

Could you elaborate on that? What would basic authentication do? And how would that be more secure?

**Comment by cemremengu** [comment]
Sorry if what I am saying does not make sense, I am new to postgrest and its concepts.

I am talking about the `Basic username:password` scheme. So by default, postgrest will require a client to provide the credentials `role_name:password(ifany)` for accessing resources. It will be more secure because users will create an anon role only if they need it (therefore optionality will be achieved too).

I think the main goal here is to provide a more flexible default auth mechanism since we cant make anon role optional without providing another default mechanism.

**Comment by wolfgangwalther** [comment]
> since we cant make anon role optional without providing another default mechanism.

Yes, we can. Anonymous access to PostgREST is not required, because the JWT tokens can be generated by another auth service, e.g. auth0.

I'm pretty sure we won't implement basic authentication. It has serious drawbacks, see e.g.:
https://security.stackexchange.com/a/990

**Comment by cemremengu** [comment]
Alright, fair enough. Then simply blocking any anon requests when `db-anon-role` is not set is the cleanest way to go (but in that case I think jwt option may be forced to prevent server being disfunctional)

Another question; is anon role really necessary? Why just not have jwt by default?

**Comment by wolfgangwalther** [comment]
> but in that case I think jwt option may be forced to prevent server being disfunctional

See https://github.com/PostgREST/postgrest/pull/2112#issuecomment-1013879569 for why I think we don't need to.



> Another question; is anon role really necessary? Why just not have jwt by default?

Anonymous access is still a good thing to have. Not everyone uses other services to create JWT tokens, so creating authentication functions that can be accessed anonymously must still be possible. And of course anonymous access in general: Some APIs are perfectly fine to request without authentication at all. And for those cases we **need** a role to run the requests with in the database.
