### ISSUE TITLE
PUT in view with partially exposed composite primary key not possible

### ISSUE THREAD

**Issue by kurt-stolle** [PostgREST/postgrest#1782]
### Environment

* PostgreSQL version: 13.2
* PostgREST version: 7.0.1
* Operating system: Ubuntu

### Description of issue

I have a schema where I want to allow users (`auth.users` table) to each have their own configuration object for a group (`grouping.groups` table). This is achieved via the following table, with composite primary keys:
```sql
create table grouping.group_configs
(
    group_id int references grouping.groups,
    user_id int   not null references auth.users default current_setting('request.jwt.claim.user_id', true)::int,
    config jsonb not null default '{}',
    primary key (group_id, user_id)
);
```
This is then exposed by the API (`v1` schema) using a view, which selects the group configs matching the current `user_id`:
```sql
create view v1.group_configs as
select group_id, config
from grouping.groups
where user_id = current_setting('request.jwt.claim.user_id', true)::int;

grant select, update, insert, delete on v1.group_configs to user_basic;
```
All HTTP methods work as expected, except those related to [upsert](https://postgrest.org/en/v7.0.1/api.html?highlight=upsert#upsert). For example, the following requests fails:
```shell
PUT http://postgrest/group_configs?group_id=eq.1
{
   "group_id": 1,
   "config": {}
}
``` 
The following error is given:
```
Filters must include all and only primary key columns with 'eq' operators
```
I expect that the issue lies in that I use a composite primary key, but I am not sure on how to resolve this. Any ideas?

**Comment by wolfgangwalther** [comment]
What happens is, that PostgREST:
- parses the view definition and tracks the columns back to their base tables,
- takes the PK of the base table, which is composite, as the virtual PK of the view
- requires the PK to be present for `PUT` as noted in the error

So the only way to make your view work with `PUT` would be to expose the `user_id` column in it, too - and then add it to the query string. Not a nice solution, though.

---

However for a config table like this, I would not use a view at all. I suggest you use 2 stored procedures:
- One to read the config for the current user (takes a group param). This could be a RPC or could also be implemented as a virtual column on the groups table instead, which would allow you to fetch the groups row + the config for this group and the current user at the same time.
- One RPC to set config options. I guess you'd actually want kind of a combination of `PUT` and `PATCH` anyway, but with modification of the `config JSONB` column, so that you could post only some config options and those will be updated, without replacing other options that are already there - and of course creating the whole document in the first place, when there is no row, yet. Creating your custom procedure solves that a lot better.
