### ISSUE TITLE
feature: Option to run PostgREST without any config

### ISSUE THREAD

**Issue by monacoremo** [PostgREST/postgrest#1823]
We currently have three remaining required config values: 

* `db-uri` - could default to postgres client [defaults](https://www.postgresql.org/docs/13/libpq-connect.html#LIBPQ-CONNECT-DBNAME), potentially even leveraging the standard env variables
* `db-schema` - could default to `public` #1769 
* `db-anon-role` - could be optional and default to Nothing (= no anonynous access) #1689

Would it be useful to have no required config? Maybe:

* Running the server with the defaults would not be functional - no request can succeed as anonymous requests are blocked and no JWT auth is set up
  * actually, that's not true is there's config in the db! So that might be worthwhile
* it would allow for quick testing of the default db connection
* would the root spec be available in that case?
* we should print a warning when neither anonymous access nor JWT is set up (that goes for #1689 generally I think)
* tools like dumpschema and dumpconfig could be used a little more easily (but only the former would really make sense)

Any thoughts? @steve-chavez @wolfgangwalther

**Comment by steve-chavez** [comment]
> db-uri - could default to postgres client defaults, potentially even leveraging the standard env variables

It'd be like `psql` right? That always works with no argument for a local pg(tcp, unix socket). I think that'd be good for a better quick start.

**Comment by wolfgangwalther** [comment]
>     * would the root spec be available in that case?

I think that depends entirely on `db-anon-role`. If you have one, it's available anonymously, otherwise only for authenticated users.

>     * we should print a warning when neither anonymous access nor JWT is set up (that goes for #1689 generally I think)

I added it to the other thread.

**Comment by wolfgangwalther** [comment]
> We currently have three remaining required config values:
> 
>     * `db-uri` - could default to postgres client [defaults](https://www.postgresql.org/docs/13/libpq-connect.html#LIBPQ-CONNECT-DBNAME), potentially even leveraging the standard env variables

I thought about this more, and I think we need to separate two issues here. Assuming schema and anonymous role are solved:
- Having `Config.configDbUri` as `Maybe Text` instead of `Text` would allow us some refactoring of our config construction - that could make it a loot easier to understand and maintain.
- Having automatic service discovery via psql env variables etc. is a nice feature to have.

However, both are actually quite independent from each other. Making `db-uri` **optional** is not really possible. Automatic service discovery would merely **construct a value for db-uri** from other parameters. In any case we'd have to throw an error if we can't get **any** db-uri from anywhere.

I think we should start with making it `Maybe Text` and then refactor the whole config construction. This will simplify a lot of things - and then we can add another step of detecting those psql env variables easily. If we decide to do that. But the refactor would be valuable in itself already.

**Comment by monacoremo** [comment]
> It'd be like psql right? 

Yes, exactly - we would aim to be fully compatible. If psql connects, postgrest will connect.

> Having Config.configDbUri as Maybe Text

Do we have to do this, though? Building an AppConfig requires a valid db-uri. We build it based on key value pairs from different sources, including psql env vars, our env vars, a config file and db config.

Potentially we would go in two stages- first parsing the db-uri, connect to load the db settings, then parse the full config.

**Comment by wolfgangwalther** [comment]
> Do we have to do this, though? Building an AppConfig requires a valid db-uri. We build it based on key value pairs from different sources, including psql env vars, our env vars, a config file and db config.

I think I should have expanded on what kind of refactoring I have in mind with that:
Making it a `Maybe` would allow us to construct a valid `AppConfig` record in the very first step already, which is not possible right now, because the requiredness of db-uri is only resolved after checking both config file and environment.

So the idea is to parse only the config file in the first step and return a valid `AppConfig` object in any case. Then any additional step (env, db-config, ...) just overrides values in this record. After the env step, we'd check for db-uri, which should be `Just` fine at this point :). If `Nothing` we throw / show usage information.

This will allow us to add a step before parsing the config file, too: Automatic service discovery. Note: Even though this relies on environment variables, it can't be in the same step as the `PGRST_` env vars, because we want the following behaviour:
- Auto-detect psql env variables
- Override the auto-detected value by anything in our config file
- Override both of those values by anything set explicitly via `PGRST_` env vars
- ... db config

Because db-uri is just `Text` and not `Maybe Text` right now and we can't provide a sane default, we have to make it "required" in the config file parser - and this makes the whole parsing logic so complicated right now, since we're kind of combining that with the environment override etc. at the same time.

> Potentially we would go in two stages- first parsing the db-uri, connect to load the db settings, then parse the full config.

I see what you mean. I think this increases complexity a tiny bit compared to my proposal - but we would not need to make db-uri a `Maybe`. In fact, in this case we should probably take db-uri out of `AppConfig` alltogether.
