### ISSUE TITLE
Differentiate between PostgREST and PostgreSQL errors in the error body

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest#1917]
**Issue**

I think the error body that the user gets does not clearly disambiguate if they come from the PostgreSQL database or from PostgREST itself. One way to know the difference is that the `code` key and its value are not present for PostgREST errors.

**Proposals**

1. A source string could be prepended to the PostgREST error message, while leaving the PostgreSQL errors untouched: 
```json
{
  "message": "PostgREST: Could not find...",
  "hint": "...."
}
```
2. Take the unused `code` key value pairs and specify that it's a PostgREST error there, leaving the rest untouched:
```json
{
  "code": "PostgREST",
  "message": "Could not find...",
  "hint": "..."
}
```
Maybe use unique codes like `PostgREST101` or `PGRST101` to identify each error.

**Comment by steve-chavez** [comment]
Sounds like a good idea. It will even make more sense when https://github.com/PostgREST/postgrest/pull/1710#issuecomment-808788905 is implemented.

> 1. A source string could be prepended to the PostgREST error message, while leaving the PostgreSQL erros untouched
> 2. Take the unused `code` key value pairs and specify that it's a PostgREST error there, leaving the rest untouched

I'd go with 2, the current error message might be used by some client libraries and we could break them.

> Maybe use unique codes like PostgREST101 or PGRST101 to identify each error.

Hm, right now I don't see the need for using codes(and seems more work to think about them), it would be good to go with just "PostgREST" as the code.

---

Implementing this will also let us document our error message body in the docs since it will be more stable.
