### ISSUE TITLE
Detect one-to-one mappings in joins to avoid sub-arrays

### ISSUE THREAD

**Issue by colearendt** [PostgREST/postgrest#1984]
### Description of issue

In some table setups, there are unique keys on both tables that establish / enforce a one-to-one mapping. Right now PostgREST joins these as an array with a single entry: `"child": [{}]`

It would be nice to have the option to join one-to-one tables as `"child": {}`

Discussed here: https://github.com/PostgREST/postgrest/pull/1978#discussion_r731153211

https://github.com/PostgREST/postgrest/blob/42d7cf8ae5b966dd901bf3695732423a9e9e2e52/src/PostgREST/DbStructure/Relationship.hs#L36-L41

**Comment by madeleineostoja** [comment]
Is there any movement or consensus on implementing this? Would be great to get a PR going

**Comment by steve-chavez** [comment]
Sure, just opened https://github.com/PostgREST/postgrest/pull/2439.

---

Adding this one later will be pain because it's strictly a breaking change(since the shape of the json output will change) and it would require a new major version bump. Users will need to revise their relationships on this release anyway(because m2m relationships changed) so it's apt to include it now.
