### ISSUE TITLE
Inaccurate total record count returned when top-level filtering with embedded resource filters

### ISSUE THREAD

**Issue by dexteradeus** [PostgREST/postgrest#2009]
### Environment

* PostgreSQL version: 9.6.2 (docker image postgres:9.6.2-alpine)
* PostgREST version: 8.0.0.20211102 (docker image postgrest/postgrest:v8.0.0.20211102)
* Operating system: Arch Linux

### Description of issue
When using `Prefer: count=exact` and filtering top-level resources based on embedded resource filters, the total record count shown in the `Content-Range` does not take into account the embedded resource filters. Filters applied to the top level resource itself are still applied, however.

I would expect that when using `count=exact` that the number of total records returned matches the total listed in the `Content-Range` header even when using filters based on embedded resources.

The issue is also present on other `count=` options.

This can be seen using a sample database from https://www.postgresqltutorial.com/postgresql-sample-database/.
The relevant schema is as follows:
```sql
CREATE TABLE public.film (
    film_id integer DEFAULT nextval('public.film_film_id_seq'::regclass) NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    release_year public.year,
    language_id smallint NOT NULL,
    rental_duration smallint DEFAULT 3 NOT NULL,
    rental_rate numeric(4,2) DEFAULT 4.99 NOT NULL,
    length smallint,
    replacement_cost numeric(5,2) DEFAULT 19.99 NOT NULL,
    rating public.mpaa_rating DEFAULT 'G'::public.mpaa_rating,
    last_update timestamp without time zone DEFAULT now() NOT NULL,
    special_features text[],
    fulltext tsvector NOT NULL
);
CREATE TABLE public.category (
    category_id integer DEFAULT nextval('public.category_category_id_seq'::regclass) NOT NULL,
    name character varying(25) NOT NULL,
    last_update timestamp without time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.film_category (
    film_id smallint NOT NULL,
    category_id smallint NOT NULL,
    last_update timestamp without time zone DEFAULT now() NOT NULL
);
ALTER TABLE ONLY public.film_category
    ADD CONSTRAINT film_category_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.category(category_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.film_category
    ADD CONSTRAINT film_category_film_id_fkey FOREIGN KEY (film_id) REFERENCES public.film(film_id) ON UPDATE CASCADE ON DELETE RESTRICT;
```

Here we see that the table has a total of 1000 records
```
$ curl -s -D - -o /dev/null -H 'Prefer: count=exact' 'http://127.0.0.1:3000/film'
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Date: Thu, 04 Nov 2021 19:12:22 GMT
Server: postgrest/8.0.0.20211102 (pre-release)
Content-Range: 0-999/1000
Content-Location: /film
Content-Type: application/json; charset=utf-8
```

Filtering by the embedded resource to show only films in the "Action" category returns the proper records, but the total record count is unchanged:
```
$ curl -s -D - -o /dev/null -H 'Prefer: count=exact' 'http://127.0.0.1:3000/film?select=*,film_category!inner(category!inner(*))&film_category.category.name=eq.Action'
HTTP/1.1 206 Partial Content
Transfer-Encoding: chunked
Date: Thu, 04 Nov 2021 19:14:58 GMT
Server: postgrest/8.0.0.20211102 (pre-release)
Content-Range: 0-63/1000
Content-Location: /film?film_category.category.name=eq.Action&select=%2A%2Cfilm_category%21inner%28category%21inner%28%2A%29%29
Content-Type: application/json; charset=utf-8
``` 
We can see that the range of records agrees with the number of records returned, it is just the total that is incorrect.
```
$ curl -s -H 'Prefer: count=exact' 'http://127.0.0.1:3000/film?select=*,film_category!inner(category!inner(*))&film_category.category.name=eq.Action' | jq '.|length'
64
```
The total does change when filtering based of a field of the top-level resource:
```
$ curl -s -D - -o /dev/null -H 'Prefer: count=exact' 'http://127.0.0.1:3000/film?select=*,film_category!inner(category!inner(*))&film_category.category.name=eq.Action&rental_duration=eq.4'
HTTP/1.1 206 Partial Content
Transfer-Encoding: chunked
Date: Thu, 04 Nov 2021 19:22:18 GMT
Server: postgrest/8.0.0.20211102 (pre-release)
Content-Range: 0-13/203
Content-Location: /film?film_category.category.name=eq.Action&rental_duration=eq.4&select=%2A%2Cfilm_category%21inner%28category%21inner%28%2A%29%29
Content-Type: application/json; charset=utf-8
```

**Comment by wolfgangwalther** [comment]
Looks like we're missing the inner joins when creating the counting query:

https://github.com/PostgREST/postgrest/blob/5cd7d35966b8e8481215ca181c7629191e7e470e/src/PostgREST/Query/QueryBuilder.hs#L178-L185

**Comment by steve-chavez** [comment]
Doing the previous count query was cheap because it only required repeating the top-level filters but for the inner joins we'd have to recurse all the sub-levels to be correct(because the next level inner join will affect the top level count), that seems more expensive.

We still have to remove the LIMIT/OFFSET from sub-levels so trying to do a CTE to not repeat the query won't help.

Hm, I wonder if doing the top-level filtering as https://github.com/PostgREST/postgrest/issues/1075#issuecomment-767457130 (and not with the inner join approach) would have helped here.

**Comment by steve-chavez** [comment]
Another thing that comes to mind is if it's really worth supporting doing the count and getting the response body at the same time.

Most use cases I've seen involve doing a HEAD request(no response body) to get the count. Because really if you have the response body in json you can do the count client side.

(btw, [our docs](https://postgrest.org/en/v8.0/api.html#exact-count) only mention doing HEAD for the count)

So if we don't support getting the count and response body at the same time, the problem of repeating an expensive query is no more.

**Comment by wolfgangwalther** [comment]
> Another thing that comes to mind is if it's really worth supporting doing the count and getting the response body at the same time.

When we're returning a response body, we could as well `COUNT(*)` on the same query results, that we aggregate the json on? The aggregation will be done anyway, an additional count should not matter much.

And then for the `HEAD` request, we can simplify the query a bit by removing left joins and only make the count aggregation.

**Comment by steve-chavez** [comment]
> When we're returning a response body, we could as well COUNT(*) on the same query results, that we aggregate the json on?

No, because the aggregated JSON has LIMIT/OFFSET applied. The total count needs those removed. 

> And then for the HEAD request, we can simplify the query a bit by removing left joins and only make the count aggregation.

This is already being done for left joins(see [above](https://github.com/PostgREST/postgrest/issues/2009#issuecomment-961678989)), the joins are stripped and also the LIMIT/OFFSET.

The problem with the inner join is that the joins cannot be stripped because they also filter the top-level.

---

For now I'm leaning towards supporting `Prefer: count=exact` only for HEAD requests in the case there's an inner on `select`. So for regular GET with inner the `Prefer: count=exact` will be ignored and the response won't contain a `Preference-Applied: count` header.

That also gives an opportunity to improve the query later in case both body and count can be obtained efficiently.

**Comment by wolfgangwalther** [comment]
> No, because the aggregated JSON has LIMIT/OFFSET applied. The total count needs those removed.

:facepalm: Of course.

> For now I'm leaning towards supporting Prefer: count=exact only for HEAD requests in the case there's an inner on select. So for regular GET with inner the Prefer: count=exact will be ignored and the response won't contain a Preference-Applied: count header.
> 
> (No breaking change)

Certainly better than returning inaccurate results.

**Comment by steve-chavez** [comment]
I've been checking if there's a more efficient count query we could use for the inner join case. A `where exists` is looking promising, for this request:

```http
GET /client?select=*,contact!inner(*),clientinfo!inner(*)
```

The generated count query would be:

```sql
SELECT 1
FROM "test"."client"
WHERE
EXISTS(
  SELECT 1 FROM "test"."contact" WHERE "test"."client"."id" = "test"."contact"."clientid"
)
AND
EXISTS(
  SELECT 1 FROM "test"."clientinfo"  WHERE "test"."client"."id" = "test"."clientinfo"."clientid"
)
```

This query would avoid repeating the unnecessary aggregations(`json_agg`) and lateral joins of the response body. Also, according to this [blog post](https://danmartensen.svbtle.com/sql-performance-of-join-and-where-exists), `where exists` can outperform an `inner join`. It also has a recursive form that would be simpler to implement.

**Comment by steve-chavez** [comment]
@wolfgangwalther Just remembered something you mentioned in https://github.com/PostgREST/postgrest/pull/1949#issuecomment-920888563.

> ... it suddenly strikes me as odd to have something in the select= part change the number of rows. Imho, the select= part should only change the shape of the output / each row - but should not filter anything.

Since WHERE EXISTS is equivalent to INNER JOIN as mentioned [above](https://github.com/PostgREST/postgrest/issues/2009#issuecomment-977473031), we could have done the syntax for top-level filtering as:

```http
GET /films?select=*,actors(*)&actors.first_name=eq.Jehanne&actors=exists HTTP/1.1
```
Instead of:

```http
GET /films?select=*,actors!inner(*)&actors.first_name=eq.Jehanne HTTP/1.1
```

Of course when doing `&actors=exists` we'd still do an INNER JOIN under the hood.

Hm, that definitely looks more RESTful and it doesn't leak the underlying mechanism(`!inner`). Should we add an additional operator for `exists`? WDYT?

**Comment by Pigeo** [comment]
> @wolfgangwalther Just remembered something you mentioned in [#1949 (comment)](https://github.com/PostgREST/postgrest/pull/1949#issuecomment-920888563).
> 
> > ... it suddenly strikes me as odd to have something in the select= part change the number of rows. Imho, the select= part should only change the shape of the output / each row - but should not filter anything.
> 
> Since WHERE EXISTS is equivalent to INNER JOIN as mentioned [above](https://github.com/PostgREST/postgrest/issues/2009#issuecomment-977473031), we could have done the syntax for top-level filtering as:
> 
> ```httpspec
> GET /films?select=*,actors(*)&actors.first_name=eq.Jehanne&actors=exists HTTP/1.1
> ```
> 
> Instead of:
> 
> ```httpspec
> GET /films?select=*,actors!inner(*)&actors.first_name=eq.Jehanne HTTP/1.1
> ```
> 
> Of course when doing `&actors=exists` we'd still do an INNER JOIN under the hood.
> 
> Hm, that definitely looks more RESTful and it doesn't leak the underlying mechanism(`!inner`). Should we add an additional operator for `exists`? WDYT?

To my understanding, these 2 syntaxes don't have exactly the same meaning, semantically speaking, and won't (shouldn't!) give the same output results.

The first syntax would retrieve films that do have at least one actor (`&actors=exists`), then embed the actors for each film, but only when `actors.first_name=eq.Jehanne`, resulting in having a lot of films with empty actors in the JSON result because they do have actors, but their first_name is not Jehanne. This follows the traditional way of how PostgREST has behaved in its previous versions.

The second syntax, however, would only retrieve films that do have at least one actor whose first_name is Jehanne (because of the `INNER JOIN`), therefore resulting most of the time in fewer results than the first syntax above. And it won't contain any empty actors in the JSON result, since each `actors` will contain at least one item with first_name Jehanne.

PS : I noticed you wrote "of course when doing &actors=exists we'd still do an INNER JOIN under the hood", but that sounds to me kind of a hack, not necessarily very user intuitive : 

```httpspec
> GET /films?select=*,actors(*)&actors=exists HTTP/1.1
> ```

Here, the intuitive reading for end users is that the query will retrieve films which are mentioned (= which do exists) in the actors table. This can be done by several ways (such as `WHERE films.id IN (SELECT film FROM actors)`, and the end user doesn't necessarily assume it's going to be implemented with an `INNER JOIN` (that might be more expensive than a `WHERE ... IN (...)`).

**Comment by Pigeo** [comment]
Just wanted to let you know that this bug is still there in PostgREST 9.0.1 (linux-static-x64, downloaded today from GitHub), but it only triggers in some special circumstances...

Let's take again the [same sample database than above](https://www.postgresqltutorial.com/postgresql-sample-database/), but suppose we now have a lot of films that don't have any category:

`DELETE FROM film_category WHERE category_id > 1; -- only 64 films will keep their category after that`

and let's add another table (`film_actor`) into play :

`http://127.0.0.1:3000/film?select=*,film_category!inner(*),film_actor(*)`

=> here, Content-Range correctly says '0-63/64'.

Now let's just change the order of the parameters inside the query string:

`http://127.0.0.1:3000/film?select=*,film_actor(*),film_category!inner(*)`

=> it should not change anything to the results / behavior, right? But now, Content-Range incorrectly says '0-63/1000' (whereas the very same 64 rows are still returned in the body)

It's not clear to me why we have to put another table in play in order to trigger the bug, but without it the bug doesn't happen:

`http://127.0.0.1:3000/film?select=*,film_category!inner(*)`

=> correctly says Content-Range '0-63/64'.


While waiting for a fix to be included in a next release, I think I found a work-around that seems to work (other than reordering the content of the `select=`, which may be not a viable solution in some contexts) : just add a dummy filter that says that the FK of the embedded table which references the main table should not be null (of course it can't be null, because we are performing an `INNER JOIN`):

`http://127.0.0.1:3000/film?select=*,film_actor(*),film_category!inner(*)&film_category.film_id=not.is.null`

=> now correctly says again Content-Range '0-63/64'.

Adding this useless dummy filter seems to change the order in which all the parameters of the `select=` are processed, as you can see on the result body (the content of the body is then "sorted" as if we had asked for `/film?select=*,film_category!inner(*),film_actor(*)` as you can see it with any diff/merge tool).

**Comment by steve-chavez** [comment]
> Just wanted to let you know that this bug is still there in PostgREST 9.0.1 (linux-static-x64, downloaded today from GitHub), but it only triggers in some special circumstances...

@Pigeo Could you open an issue for that one?
