### ISSUE TITLE
Option to disallow views

### ISSUE THREAD

**Issue by nerfpops** [PostgREST/postgrest#2124]
I have seen developers create views, not knowing that RLS wouldn't be enforced and thereby leaking data. The incident was caught before going to production so nothing happened, but it made me think that this could have been prevented by having an option to not allow views, or simply not expose them. I don't ever create views because of this, and ideally PostgREST would provide a way to disable creating endpoints for them.

**Comment by wolfgangwalther** [comment]
I don't think we'll do something like that on the PostgREST level.

You could try creating an event trigger on `ddl_command_start`, check that this is about to create a view in your api schema - and then raise an error.

**Comment by dwagin** [comment]
Totally agree, this should not be part of PostgREST.

**Comment by nerfpops** [comment]
Good point.

**Comment by wolfgangwalther** [comment]
> I have seen developers create views, not knowing that RLS wouldn't be enforced and thereby leaking data.

fyi, this is not entirely true. As long as:
- your view owner is not a superuser,
- your view owner does not have bypass rls privileges and
- your view owner is different from the table owner

you can make views work with RLS.

You will need to create the policies `TO public` or `TO view_owner`  and can't use different policies for different api users. But you can use `CURRENT_USER` as expected in the policy's `USING` and `WITH CHECK` clauses.

See also https://github.com/PostgREST/postgrest-docs/issues/400 for more details about slightly different behavior when using `INSTEAD OF` triggers, auto-updateable views and `DO INSTEAD` rules.

**Comment by steve-chavez** [comment]
Hm, this is a problem. Another way to prevent it could be running pgtap tests before deploying a migration to production, checking in the tests that no view owner is a superuser or bypassrls.

**Comment by nerfpops** [comment]
@wolfgangwalther But in views it's the other way around: instead of applying RLS for the jwt role, the role used when creating the view is applied. If a developer is already aware of this, then there's no problem

**Comment by wolfgangwalther** [comment]
> But in views it's the other way around: instead of applying RLS for the jwt role, the role used when creating the view is applied. 

Not entirely "the other way around".

Take this example:

```sql
CREATE POLICY <name> ON <my_table>
  FOR ALL TO view_owner
  USING (<my_col> = CURRENT_USER);
```

When you access the table through the view:
- when deciding **which** policy to apply, PG will use the view owner
- but when evaluating the policy's clause, `CURRENT_USER` will **not** be the view owner, but still the user making the query (api / jwt user)

So this somewhere inbetween. It is quite counter-intuitive, though.

So taking Steve's suggestion even further, you could write pgTAP tests, that:
- Test each view to have the correct owner (`view_owner`)
- Test each policy to be created `TO view_owner`

From there it's just about using `CURRENT_USER` in the policy - and that part is intuitive.
