### ISSUE TITLE
Scary JWT behiavour

### ISSUE THREAD

**Issue by wiwwo** [PostgREST/postgrest#2137]
Hi!
Not sure what I am doing wrong, but this is "funny"

```
$ export TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidGVybWlubGFuZCJ9.ZI0wVChgJ0yk2QmX3-bkXyv8SJ4coTubz4vSurmvX3Y"
$ curl http://localhost:3000/rpc/whoami -X GET -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json"
"user-01"
```

I change the last character of the TOKEN from `Y` to `S`
```
$ export TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidGVybWlubGFuZCJ9.ZI0wVChgJ0yk2QmX3-bkXyv8SJ4coTubz4vSurmvX3S"
$ curl http://localhost:3000/rpc/whoami -X GET -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json"
{"message":"JWSError JWSInvalidSignature"}
```

I change the last character of the TOKEN from `S` to `Z`
```
$ export TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidGVybWlubGFuZCJ9.ZI0wVChgJ0yk2QmX3-bkXyv8SJ4coTubz4vSurmvX3Z"
$ curl http://localhost:3000/rpc/whoami -X GET -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json"
"user-01"
```

Is this expected?

**Comment by wolfgangwalther** [comment]
Yes, this is perfectly fine.

It's a result of how base64 encoding works. The decoded token has 80 characters, each holding 8 bits of information, for a total of 640 bits. Base64 only has 6 bits per character, because of the reduced character set. 640 is not divisible by 6. It's 106.66...

The base64 string has a length of 107 characters, though - that's an additional 2 bits. That means that the last 2 bits don't carry any information.

Here's the binary representation of Y, S and Z:
```
S 01010011
Y 01011001
Z 01011010
```

Note how you changed only the last two bits when changing Y to Z - and how you changed one of the other bits with the S.

Decoding the three tokens you gave results in:
```
{"alg":"HS256","typ":"JWT"}{"role":"terminland"}d0T(`'L¤Ù	ßæä_+üH¡;ÏÒº¹¯_v

{"alg":"HS256","typ":"JWT"}{"role":"terminland"}d0T(`'L¤Ù	ßæä_+üH¡;ÏÒº¹¯_t

{"alg":"HS256","typ":"JWT"}{"role":"terminland"}d0T(`'L¤Ù	ßæä_+üH¡;ÏÒº¹¯_v
```

Note how the first and last token are the same once decoded. The second modification modifies the signature of the token, though, and that's why authentication fails.
