### ISSUE TITLE
Don't fail on RPC with`Accept: text/plain, application/json`

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#2170]
A request like :

```http
GET /rpc/jsonfunc
Accept: text/plain, application/json
```

Gives `406 Not Acceptable`. We prefer `text/plain` in this case because both `q` values are 1.0 by default and there's an order preference. If it were `Accept: text/plain; q=0.2, application/json; q=0.8`, then `application/json` would be picked and the request would succeed.

The RFC doesn't specify that ordering is relevant according to this [so answer](https://stackoverflow.com/a/47196708/4692662). So we could give preference to `application/json` over `text/plain`, because the latter is only supported on certain conditions while the former is supported on every request.

The problem comes from https://github.com/PostgREST/postgrest/discussions/2162#discussioncomment-2193532.

This might require patching [parseHttpAccept](https://hackage.haskell.org/package/wai-extra-3.1.8/docs/Network-Wai-Parse.html#v:parseHttpAccept).

**Comment by wolfgangwalther** [comment]
I think we need to separate two issues here:
- The bug in #2162 seems to be, that we are treating content negotiation (deciding which mediatype to respond to) and "finding the right function to call for this request" separately - while they need to merged into one. Before deciding for any of the mimetypes listed in the `Accept` header, we need to see which of those are actually actionable for the given set of arguments etc. - in this case, it would only be `application/json`, because there is no function found that can handle a `text/plain` type. But we settle on `text/plain` way too early right now - before we even look into the list of functions.
- The other question is what should happen, when both of the given mimetypes are indeed acceptable, i.e. we have overloaded functions that could handle both mimetypes and they do have the same priority. You suggest that we should give priority to `application/json` in this case - and I don't think we should. From a set of equally weighted types, it would be absolutely fine to choose the first one that is possible to choose.

**Comment by steve-chavez** [comment]
> Before deciding for any of the mimetypes listed in the Accept header, we need to see which of those are actually actionable for the given set of arguments etc
> From a set of equally weighted types, it would be absolutely fine to choose the first one that is possible to choose.

Agree with both :+1:
