### ISSUE TITLE
Health check returns 503 even if PostgREST is running correctly unless the `server-host` config is set to `localhost`

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest#2174]
### Environment

* PostgreSQL version: 13.5
* PostgREST version: 9.0.0.20220211
* Operating system: EndeavourOS - Linux 5.16.10-arch1-1

### Description of issue

After setting the configuration variable `admin-server-port` to `3001` I tested the health check by doing a `curl -I "http://localhost:3001/live` and the response I got was `HTTP/1.1 503 Service Unavailable` (it was the same for the `/ready` endpoint), even though  the PostgREST service at the `3000` port was working correctly.

I did a debug trace to this line of code:

https://github.com/PostgREST/postgrest/blob/dcf7ade5bc70a31fe0e083e1527b74125a94aeda/src/PostgREST/Admin.hs#L24

and the PostgREST service returns this as a result of the health check:

```haskell
Left Network.Socket.getAddrInfo 
  (called with preferred socket type/protocol: 
    AddrInfo {addrFlags = [], 
              addrFamily = AF_UNSPEC, 
              addrSocketType = Stream, 
              addrProtocol = 0, 
              addrAddress = <assumed to be undefined>, 
              addrCanonName = <assumed to be undefined>}, 
              host name: Just "!4", 
              service name: Just "3000"): 
  does not exist (Name or service not known)
```

Changing the `server-host` to `*` gave a different error:

```haskell
Left Network.Socket.connect: <socket: 16>: does not exist (Connection refused)
```

What worked was to set the `server-host` to `localhost` or `127.0.0.1`, only then the health check returned `200 OK` as expected.

Perhaps this is an issue with my distro, but still, maybe some logs are required to inform admins of the possible error?

**Comment by wolfgangwalther** [comment]
> Perhaps this is an issue with my distro

Don't think so, I can reproduce easily.

The problem is in the special values for `server-host`. Those are handled by [`bindPortTCP`](https://hackage.haskell.org/package/streaming-commons-0.2.2.4/docs/Data-Streaming-Network.html#g:8) - but obviously not by the code that tries to connect to the main socket.

I think the proper solution would be to:
- Replace [`runSettings` with `runSettingsSocket`](https://hackage.haskell.org/package/warp-3.3.19/docs/Network-Wai-Handler-Warp.html#g:1) - and call `bindPortTCP` ourselves.
- Keep the listen socket returned by `bindPortTCP` somewhere - probably `AppState` or so?
- Use this socket to connect to from the admin health check - this way we don't need to use `getAddrInfo` at all, because we already have access to the same socket the clients will use to connect.
- Bonus: Can we extract the listening host from the socket? If yes, we could extend the "listening on port xyz" message to include the host/ip.

**Comment by wolfgangwalther** [comment]
I hit the same bug when deploying PostgREST to kubernetes. The health check is essentially unusable on kubernetes, afaik. I think we should fix this before releasing the admin server / health check.
