### ISSUE TITLE
Builds using cabal throw errors (ambiguous types)

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest#2301]
### Environment

* PostgreSQL version: 14.3
* PostgREST version: 9.0.0.20220531/ main 807364bd7b2adfcfc0e2ebc5efccd5150dc45652
* Operating system: ubuntu-arm64 / EndeavourOS

### Description of issue

Running `cabal v2-update && cabal v2-install` throws errors on some modules as seen on the [latest ARM builds in the GitHub CI](https://github.com/PostgREST/postgrest/runs/6729509695?check_suite_focus=true#step:8:123). Also, testing on older versions (which already run without problems before) are now giving the same errors.

Looks like Cabal needs explicit casting to avoid the ambiguity, but can't figure out why now.

**Comment by robx** [comment]
I think this is due to the release of Protolude 0.3.1. https://hackage.haskell.org/package/protolude-0.3.1.

I agree that it would be good to have a CI job that builds (or maybe just plans a build?) with cabal against up-to-date hackage, so that we notice such things explicitly.

And in the other direction, I suppose ideally the ARM build would use the same dependency versions as the other CI jobs. Could we achieve that by generating a cabal.project.freeze file from the nix setup?
