### ISSUE TITLE
Bogus `Listening on port 0` message, provide useful info

### ISSUE THREAD

**Issue by strk** [PostgREST/postgrest#2420]
I'm willing to find a random available port for my postgrest service, so I run:
```
PGRST_SERVER_PORT=0 postgrest postgrest.conf
```

It works fine, except then I'm left alone in figuring out which port the kernel assigned to the socket, becuase postgrest just reports:
```
10/Aug/2022:17:31:57 +0200: Listening on port 0
```

Maybe the message should advertise the actual port being used ?

**Comment by wolfgangwalther** [comment]
This is very similar to #2174. This was fixed in #2182. That same approach won't work here, I think.

If we had fixed that according to https://github.com/PostgREST/postgrest/issues/2174#issuecomment-1045978929, we'd have the code in place to extract the actually used port, too.

I think we should fix both together: I.e. always extract the actual host and port used and not guess anything.

**Comment by develop7** [comment]
Going a little further, can the `server-port` setting be optional at all then?

**Comment by steve-chavez** [comment]
Right now `server-port` is optional because we default it to 3000. Hm, not sure if we should change the default to 0 because that would also imply changing the docs in several places.

**Comment by develop7** [comment]
Oh, I forgot that. That'd be a breaking change indeed.
