### ISSUE TITLE
Connection error - Database does not exists after patching to a newer version

### ISSUE THREAD

**Issue by jeanpierre92** [PostgREST/postgrest#2970]
### Environment

* PostgreSQL version: (if using docker, specify the image)
*  15.4(container)
* PostgREST version: (if using docker, specify the image)
* 11.2.0 and 11.1.0(container)
* Operating system:

### Description of issue

From PostgREST version 11.0.1 the api can connect to the database via the config:

PGRST_SERVER_PORT=2888
PGRST_DB_URI=postgres://forecasting:<PW_HERE>@<HOST_HERE>:5432/forecasting
PGRST_DB_SCHEMA=api
PGRST_DB_ANON_ROLE=forecasting

But after patching to the next version I see errors:

26/Sep/2023:13:14:51 +0200: {"code":"PGRST000","details":"connection to server at \"<HOST_HERE>\" (10.8.106.143), port 5432 failed: FATAL:  database \"forecasting fallback_application_name='PostgREST 11.2.0'\" does not exist\n","hint":null,"message":"Database connection error. Retrying the connection."}

I see the same errors in the logging in the postgresql database logging. The config has not changed between versions.

**Comment by steve-chavez** [comment]
Likely caused by:

- https://github.com/PostgREST/postgrest/issues/2647
- https://github.com/PostgREST/postgrest/pull/2740

@jeanpierre92 Are there special characters in `PW_HERE` or `HOST_HERE`?

**Comment by jeanpierre92** [comment]
@steve-chavez Yes, in the password there are chars like: "=)[&", the host does not have special chars.

**Comment by laurenceisla** [comment]
I tested this and the solution should be to change those special characters to percent-encoded characters, e.g. `=)[&` to `%3D%29%5B%26`.

I can confirm that percent-encoding was not needed in `v11.0.1`. PostgREST didn't check if it's a valid URI and sent it directly to the connection library, which maybe sent the URI string as-is to the database. 

 In `v11.2.0`, the password MUST be percent encoded, because now a library checks first if the URI is valid (which is not if it has those special characters). Not sure if it should be considered a breaking change, the docs suggested that the password [should be percent encoded](https://postgrest.org/en/v11.0/references/configuration.html#db-uri).

**Comment by steve-chavez** [comment]
Just to clarify. To add the `fallback_application_name`, the code is considering that the connection string is not a valid [URI format](https://postgrest.org/en/stable/references/configuration.html#uri-format), and then it assumes it's in [key-value format](https://postgrest.org/en/stable/references/configuration.html#keyword-value-format). This is what gives the weird error message.

https://github.com/PostgREST/postgrest/blob/a6e3eda5b20817f134beb8d660029bd2875c280f/src/PostgREST/Config.hs#L499-L505

This needs to be fixed somehow, because if previous versions did connect then it was indeed a valid URI.

---

Something that's weird is that some special non-urlencoded characters do cause an error when connecting, see: 
- https://github.com/PostgREST/postgrest/issues/1244

Seems the connection only fails on a non-urlencoded `@`?
