### ISSUE TITLE
Configuration for server-timing

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#3062]
## Problem

Right now `Server-Timing` header is enabled by [db-plan-enabled](https://postgrest.org/en/stable/references/configuration.html#db-plan-enabled) but it shouldn't. The [execution plan](https://postgrest.org/en/stable/references/admin.html#execution-plan) can be used independently.

https://github.com/PostgREST/postgrest/blob/91d53852370f5bf5ef1ecaa69b9ee7b8435b63a1/src/PostgREST/App.hs#L261-L267

## Solution

Enable `Server-Timing` with a `server-timing-header` configuration instead.

(We have a similar config https://postgrest.org/en/stable/references/configuration.html#server-trace-header)

**Comment by develop7** [comment]
`server-timing-header` suggests the parameter type is `String` and the header name is configurable (which isn't really, since it'd fixed in the standard), similar to `server-trace-header`. Could it be `server-timing-enabled` instead, similar to `db-plan-enabled`, retaining the existing naming scheme?

**Comment by steve-chavez** [comment]
> Could it be server-timing-enabled instead, similar to db-plan-enabled, retaining the existing naming scheme?

Yup, sounds better!
