### ISSUE TITLE
OpenAPI does not tag a column as FK if it also has a UNIQUE constraint

### ISSUE THREAD

**Issue by laurenceisla** [PostgREST/postgrest#3418]
### Environment

* PostgreSQL version: 15.6
* PostgREST version: 12.0.2
* Operating system: NixOS

### Description of issue

When a Foreign Key column is detected, OpenAPI adds the description "Note: This is a Foreign Key..." to it. But if that column also has a UNIQUE constraint, then it does not show that description anymore, e.g.:

This column shows the message:
```sql
todo_id int references api.todos(id)
```

While this doesn't:
```sql
todo_id int references api.todos(id) unique
```

**Comment by softmarshmallow** [comment]
Hi @laurenceisla . I have a follow up question regards to this issue and PR

I've managed to parse the fk data, but still cannot tell if its a unique one. (if it returns non array)

**Q: can we get a example description output when the fk is unique ?**

Before:
```json
"description": "Note:\nThis is a Foreign Key to `foreign.id`.<fk table='foreign' column='id'/>",
```

After:
```
?
```


**Q: Is this a PR that I think it is? - I am trying to parse the one-to-one metadata, but since the properties does not contain additional metadata if it is uniqye other than if its a pk.**

Is this issue answers my question or should I open a new issue for having `unique` metadata in description?


Thank you : )

**Comment by laurenceisla** [comment]
@softmarshmallow 

> Is this a PR that I think it is?

The main issue was that the "Note: This is a Foreing Key...." message was not showing at all. You wouldn't know if it was a foreign key when it had UNIQUE.

> ... or should I open a new issue for having unique metadata in description?

So, yes, opening a new issue is better.
