### ISSUE TITLE
Clean up arm job when run again

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/postgrest#3532]
The following scenario just happend:
- The arm job failed on main
- The cleanup job still ran, because it's always running
- I triggered a re-run of arm

Now.. the cleanup will not happen anymore, so the build directory will be kept forever.

**Comment by laurenceisla** [comment]
Ah, so something like this?

1st CI run: Arm build :x: -> Clean up job :white_check_mark: 
2nd CI run: Arm build :white_check_mark: -> Clean up job :no_entry_sign:

But I think the cleanup still run, there's no directory in the server right now, or did you delete it manually? It should still trigger when it's rerun due to the dependency.
