### ISSUE TITLE
Progress OpenAPI 3.0?

### ISSUE THREAD

**Issue by shania-g** [PostgREST/postgrest#3678]
Hi, I just wanted to ask what progress is being made on supporting the newer OpenAPI 3.0 specification?

I have seen that there is https://github.com/PostgREST/postgrest-openapi/ but I am not sure if this is still being actively worked on.

I really like PostgREST, and it works well with Swagger 2.0, but nowadays there are several tools and libraries that require the newer specification, so I think it would be very important to support that in the near future.

I know that there is the workaround with using the official swagger converter, but having to proxy beforehand so that works is not very elegant.

Thank you :)

**Comment by laurenceisla** [comment]
> I have seen that there is https://github.com/PostgREST/postgrest-openapi/ but I am not sure if this is still being actively worked on.

Hi! Yes, that is the new OpenAPI 3.0 project for PostgREST and it's currently in development. There aren't much updates lately due to other features being implemented in the core repository, but it is not abandoned by any means.

I'm closing this issue since this is already tracked in #1698 (I'll edit its title to mention the 3.0 version).

**Comment by shania-g** [comment]
Alright, thank you for the confirmation. I just wanted to make sure, as I do think that this should have a high priority.
