### ISSUE TITLE
new feature - control tables/views currentuser insert, delete. update rights

### ISSUE THREAD

**Issue by jyritali** [PostgREST/postgrest#3684]
feature: control tabel/view currentuser insert, update,delete rights.
add to PostgREST - user tabel and view rights control and show methods reagarding user rights, not table or view one

**Comment by laurenceisla** [comment]
I'm closing this issue since the methods returned by `OPTIONS` do not depend on the privileges of the tables/views as explained in my comment in the linked PR: https://github.com/PostgREST/postgrest/pull/3685#issuecomment-2276332801

If this is about the OpenAPI output showing methods that are not allowed for a user, then this can be tracked in #1870

**Comment by jyritali** [comment]
Is there any option to achive this with postgres (show methods regarding user rights)?
Or I just made these code changes little bit wrong place in code?

Or I just have to wait when this https://github.com/PostgREST/postgrest/issues/1870 will be resolved? 

Yes, I know always is option to make own codeset and build itself postgres, but this is not best option, if I want get new updates and bugfixes

**Comment by laurenceisla** [comment]
> @laurenceisla Is there any option to achive this with postgres (show methods regarding user rights)?
> Or I just made these code changes little bit wrong place in code?

Yes, the query you modified is not the right place when you need to apply privileges. That's because it's using the `authenticator` role, so it would not return the expected results in the OpenAPI output if you use a different `anonymous` user.

This is the relevant query:

https://github.com/PostgREST/postgrest/blob/6c7963c1c4b419bff14f1f6e5df17f57f3070897/src/PostgREST/SchemaCache.hs#L476-L478

The result of that query is used to filter the tables in the schema cache:

https://github.com/PostgREST/postgrest/blob/6c7963c1c4b419bff14f1f6e5df17f57f3070897/src/PostgREST/Query.hs#L178-L181

Any change to include privileges should be done there.

> Or I just have to wait when this https://github.com/PostgREST/postgrest/issues/1870 will be resolved?

All in all, yes, that issue would be solved by modifying what I mentioned above, but I don't think it's a trivial change and requires some refactoring. That's why we are not planning on solving this issue here in core but in the [`postgrest-openapi` repo](https://github.com/PostgREST/postgrest-openapi). Here's extra explanation https://github.com/PostgREST/postgrest/issues/1870#issuecomment-856928468
