### ISSUE TITLE
Slow query, possibly due to regex, affects start-up time severely

### ISSUE THREAD

**Issue by krueger71** [PostgREST/postgrest#945]
The sql-query in the function 
```haskell
allSynonyms :: [Column] -> H.Query () [(Column,Column)]` 
```
in [src/PostgREST/DbStructure.hs](https://github.com/begriffs/postgrest/blob/build-0.4.2.0/src/PostgREST/DbStructure.hs) runs very slowly in 0.4.1.0/0.4.2.0 compared to version 0.4.0.0 and 0.3.2.0.

The single change of the query between 0.4.0.0 and 0.4.1.0/0.4.2.0 is the following expression containing a regex:

```sql
diff sql-0.4.0.0.sql sql-0.4.1.0.sql
50c50
<                     CONCAT('SELECT.*?((',vcu.table_name,')|(\w+))\.(', vcu.column_name, ')(\s+AS\s+("([^"]+)"|([^, \n\t]+)))?.*?FROM.*?',vcu.table_schema,'\.(\2|',vcu.table_name,'\s+(as\s)?\3)'),
---
>                     CONCAT('SELECT.*?((',vcu.table_name,')|(\w+))\.(', vcu.column_name, ')(\s+AS\s+("([^"]+)"|([^, \n\t]+)))?.*?FROM.*?(',vcu.table_schema,'\.|)(\2|',vcu.table_name,'\s+(as\s)?\3)'),
```
Analyzing that line further one can see that the new version has only one change, which is this capture group expression `(',vcu.table_schema,'\.|)`.  

Query times on my particular database schema is around 11 s with 0.3.2.0, 15 s with 0.4.0.0 and a huge slow-down to 430 s in 0.4.1.0/0.4.2.0. Postgrest is unresponsive or throwing errors until this query has finished.

**Comment by ruslantalpa** [comment]
@krueger71 can you attach a sample (big) schema that exposes this problem?
you can try your schema and rename to gibberish all the table/column names. 
the important part is to see how this query performs on the schema

**Comment by cbandy** [comment]
The change made matching on `vcu.table_schema` optional. If that's okay, then I think we can just remove this group completely. The preceding `.*?` will cover it, and only the column name and alias are needed from the captures.

**Comment by steve-chavez** [comment]
Was thinking that this query could be optimized by using the [pg_depend](https://www.postgresql.org/docs/10/static/catalog-pg-depend.html) catalog instead of the regex, but according to http://bonesmoses.org/2014/11/05/on-postgresql-view-dependencies/ with this catalog:
> we can discover what the aliases depend on, but not what the aliases are. I can’t really think of any reason this would be set for tables, but not for views.

**Comment by steve-chavez** [comment]
Can't come up with a way to meaningfully optimize the `allSynonyms` query, I don't think that can be done without pg adding support for detecting view source columns in `pg_depend`.

So how about this:

- Impose an additional restriction for view embeds to work: **the view must not rename the foreign key columns**, this way we can drop the regex, since there's no alias the view col is the same as the table col, and we could use `pg_depend` or maybe just use `information_schema.view_column_usage`.

- To maintain backwards compatibility for now we could add a `view-embed-allow-fk-cols-rename` config value, default `true`.

I think is a reasonable limitation and the user can rename the cols through pgrst querystring if needed.

**Comment by ejdoming** [comment]
Of course, @steve-chavez 


Unique  (cost=1086.66..1086.91 rows=17 width=224) (actual time=698.165..723.925 rows=5679 loops=1)
  ->  Sort  (cost=1086.66..1086.70 rows=17 width=224) (actual time=698.158..705.919 rows=5679 loops=1)
        Sort Key: ((nv.nspname)::information_schema.sql_identifier), ((v.relname)::information_schema.sql_identifier), ((nt.nspname)::information_schema.sql_identifier), ((t.relname)::information_schema.sql_identifier), ((a.attname)::information_schema.sql_identifier)
        Sort Method: quicksort  Memory: 1125kB
        ->  Hash Join  (cost=624.41..1086.31 rows=17 width=224) (actual time=29.439..564.434 rows=5679 loops=1)
              Hash Cond: (dv.refobjid = v.oid)
              ->  Nested Loop  (cost=439.03..898.11 rows=527 width=196) (actual time=21.230..517.475 rows=5679 loops=1)
                    ->  Nested Loop  (cost=438.75..880.55 rows=19 width=200) (actual time=21.200..160.461 rows=5682 loops=1)
                          ->  Hash Join  (cost=438.46..795.60 rows=72 width=144) (actual time=20.924..57.746 rows=6305 loops=1)
                                Hash Cond: (dt.refobjid = t.oid)
                                ->  Bitmap Heap Scan on pg_depend dt  (cost=241.51..586.41 rows=3072 width=12) (actual time=10.693..23.901 rows=6305 loops=1)
                                      Recheck Cond: (classid = '2618'::oid)
                                      Filter: (refclassid = '1259'::oid)
                                      Rows Removed by Filter: 155
                                      Heap Blocks: exact=74
                                      ->  Bitmap Index Scan on pg_depend_depender_index  (cost=0.00..240.74 rows=6460 width=0) (actual time=10.617..10.617 rows=6460 loops=1)
                                            Index Cond: (classid = '2618'::oid)
                                ->  Hash  (cost=194.13..194.13 rows=226 width=132) (actual time=10.180..10.180 rows=677 loops=1)
                                      Buckets: 1024  Batches: 1  Memory Usage: 117kB
                                      ->  Hash Join  (cost=1.14..194.13 rows=226 width=132) (actual time=0.441..8.389 rows=677 loops=1)
                                            Hash Cond: (t.relnamespace = nt.oid)
                                            ->  Seq Scan on pg_class t  (cost=0.00..190.48 rows=226 width=72) (actual time=0.192..5.753 rows=677 loops=1)
                                                  Filter: (pg_has_role(relowner, 'USAGE'::text) AND (relkind = ANY ('{r,v,f,p}'::""char""[])))
                                                  Rows Removed by Filter: 2038
                                            ->  Hash  (cost=1.06..1.06 rows=6 width=68) (actual time=0.218..0.218 rows=47 loops=1)
                                                  Buckets: 1024  Batches: 1  Memory Usage: 13kB
                                                  ->  Seq Scan on pg_namespace nt  (cost=0.00..1.06 rows=6 width=68) (actual time=0.036..0.111 rows=47 loops=1)
                          ->  Index Scan using pg_attribute_relid_attnum_index on pg_attribute a  (cost=0.29..1.18 rows=1 width=70) (actual time=0.011..0.011 rows=1 loops=6305)
                                Index Cond: ((attrelid = dt.refobjid) AND (attnum = dt.refobjsubid))
                    ->  Index Scan using pg_depend_depender_index on pg_depend dv  (cost=0.29..0.91 rows=1 width=8) (actual time=0.054..0.057 rows=1 loops=5682)
                          Index Cond: ((classid = '2618'::oid) AND (objid = dt.objid))
                          Filter: ((refclassid = '1259'::oid) AND (deptype = 'i'::""char"") AND (refobjid <> dt.refobjid))
                          Rows Removed by Filter: 57
              ->  Hash  (cost=181.50..181.50 rows=310 width=132) (actual time=8.123..8.123 rows=310 loops=1)
                    Buckets: 1024  Batches: 1  Memory Usage: 58kB
                    ->  Hash Join  (cost=1.14..181.50 rows=310 width=132) (actual time=0.429..4.677 rows=310 loops=1)
                          Hash Cond: (v.relnamespace = nv.oid)
                          ->  Seq Scan on pg_class v  (cost=0.00..176.91 rows=310 width=72) (actual time=0.192..3.366 rows=310 loops=1)
                                Filter: (relkind = 'v'::""char"")
                                Rows Removed by Filter: 2405
                          ->  Hash  (cost=1.06..1.06 rows=6 width=68) (actual time=0.198..0.198 rows=47 loops=1)
                                Buckets: 1024  Batches: 1  Memory Usage: 13kB
                                ->  Seq Scan on pg_namespace nv  (cost=0.00..1.06 rows=6 width=68) (actual time=0.024..0.094 rows=47 loops=1)
Planning time: 17.374 ms
Execution time: 732.777 ms

**Comment by ruslantalpa** [comment]
@steve-chavez i would say projects with with hundreds of views and thousands of columns are much less common (and maybe indicative of other problems) then projects that use the full power of the views (which means having the ability to rename columns)

We usually say "you can use views to decouple your data model from the api", if you remove the ability to rename columns, that statement is no longer true (only truish ) .

But, the thing you propose actually the ability to chose between 2 hardcoded queries, which is les powerful then being able to provide your own query.

Here is the (long term direction) method that is both very flexible, powerful and simple (doe not mean it a few lines, it's a full rewrite of a few core parts).

- define a data structure that fully describes the database schema (to the extend we need the info)
- define a json instance for it so that we can translate between the two easely
- write a single query (combine all the current ones, it's possible) that will return the schema layout in json format as described above.

once the above things are working, one can add a config param (file path) that depending on the extension (json/sql) reads the database structure from either the hardcoded json or by runnig the query from the file (that returns the json in the expected format)

This opens up a lot of possibilities, specifically defining (embed) relations that are not defined by FK for some reason.

anyway ... this is the long term vision, and it will take a while to implement it but imo it the best way for how to solve this

short term solution
a) i am sure the query can be optimised, the number of rows being joined on which the regex is executed i think grows exponentially with the number of views/columns, we could make it linear i think
b) ppl with these types of structures, can change the query in the code to a simple select from a materialized view of this complicated query and build a custom version of postgrest

**Comment by steve-chavez** [comment]
@ruslantalpa Projects with non-trivial business domains(government systems, ERP) will have complex databases(hundreds of tables, many columns), those don't mean design problems, also in particular the idea of connecting to a big legacy database and be able to create an api schema is what drew me to PostgREST, I'd say these dbs are a major use case while though are more cases of trivial dbs(that could also get complex with age). We should support this use case out of the box(no custom postgrest version) with fast DbStructure queries. 

The subselect limitation for views embedding is already there so users are not using the full power of views and in fact if we go with my proposal we would have more of that power since the only limitation would be the **fk cols renames(didn't say all columns)** and users could still use subselects(`view_column_usage` detect the source cols and if they are in the top level of the query the join will succeed). 

My idea is also that this proposal should eventually replace the regex query and become the default(new config value gone), this view embed behavior is more understandable(`pg_depend` known limitation, easier to document)/powerful and the query fast enough for big db use cases.

**Comment by steve-chavez** [comment]
About your long term vision:
> But, the thing you propose actually the ability to chose between 2 hardcoded queries, which is les powerful then being able to provide your own query.

Having a single sql file that outputs the DbStructure in json is something I thought as well but more as means for easier maintenance but providing a way to override that through a config value gives place for users to make mistakes and add more support burden.

> This opens up a lot of possibilities, specifically defining (embed) relations that are not defined by FK for some reason.

Don't see the need for that, could be abused and expose expensive joins and as of now users can do the same with views and have arbitrary joins.

In general, what your vision covers is more of a theoretical use case, my view is that the less ways to configure PostgREST it's the better for UX and not worrying about having to debug it.

**Comment by steve-chavez** [comment]
Was thinking that if we would have a `MATERIALIZED VIEW` as the DbStructure input we could obviate the `SIGHUP` and let the user do the db cache refreshing with just SQL, a `REFRESH MATERIALIZED VIEW` and then PostgREST would LISTEN to that event, unfortunately that's not currently supported according to the [event matrix](https://www.postgresql.org/docs/current/static/event-trigger-matrix.html)

Could be powerful to have a materialized view as the DbStructure because besides being fast it would be more discoverable(users have been asking how to see PostgREST inferred relationships between tables for embedding) since we could bring back the json root url output `/` and then our traditional filters would be available on this(`/?table=eq.smth`).

**Comment by steve-chavez** [comment]
I've been checking the project's history and I've noticed that the main motivation for having this regex is for detecting renaming of foreign key columns in a camelCase way and still be able to embed views, see https://github.com/PostgREST/postgrest/pull/353.

So I think we could enhance my [proposal](https://github.com/PostgREST/postgrest/issues/945#issuecomment-380839539) and allow renaming foreign key columns but just to their camelCase/uppercase equivalents, this duck type check would be done in Haskell code(maybe add these equivalents as `synonyms` in our schema cache)  and we could drop the regex sql query and just use `information_schema.view_column_usage`.

I'm leaning towards this change and not add a new config value, the old PR use case is still supported and users can rename the columns through PostgREST, so we could just announce the breaking change and release it in `v6.0.0`.

**Comment by barbalex** [comment]
I _think_ this could be the reason postgrest needs _hours_ to start up (until it logs "connection successfull") on my database.

This has become an absolute killer for our use case. Which is why I am actively migrating to postgraphql which takes two seconds to start up.

I have spent hours searching for any one else having this problem. And this seems the most likely candidate. Our database has hundreds of views because:

- we run 100 quality-check-views so users can check the quality of their data periodically
- we use views for exports (a few dozen)
- we use views to prepare data for MS-Access which is unfortunately still used for some Jobs. And because MS-Access is incredibly slow we need to prepare all data server side with views instead of using queries in MS-Access

Startup time is now:

- between two to four hours in the live server
- a few dozen minutes on my local machine

Because of the hours it takes to start up on the live server this is a massive headache if postgrest hast to be restarted.

Our data is not open source (as opposed to the code). But if you promise to be mindful I can send you a copy of the db for testing purposes.

**Comment by krueger71** [comment]
Using a separate api-schema, served by Postgrest, on top of a data schema with the relational model worked really well for us in a small government system backend. We would not have used Postgrest unless we had the possibility to layer the access to the data in this way. Apart from this start-up performance issue (which we avoided by not upgrading from 0.4.0.0) it has been extremely straightforward to develop our backend. We saw the views in the api-schema as aggregates in the domain-driven design sense. Some  which needed update-capabilites via instead-of triggers. In combination with the sql security model we ended up with a database that we almost could have let end-users have access to from the prompt. Other clients that only could communicate on a database level (e.g. QGis) could connect and use the same views, centralizing "business logic" in a way that is hard to achieve with more conventional architectures. There's a lot of benefits in using Postgrest, especially if you are comfortable with relational design.

The start-up performance can make-or-break Postgrest's use in these kinds of systems. I can easily imagine many larger systems ending up with hundreds of views on top of hundreds of tables without it being an indication of bad design. It's just how it is when laws and other complex domains are coded into information systems. It gets big and hairy because of the complexity and lack of orthogonal concepts.

**Comment by steve-chavez** [comment]
Sorry about the inconveniences caused @barbalex, if you could send me a copy of only your db schemas, **no data required**(you can use `pg_dump --schema-only your_db > big_schema.sql`), that would help me in fixing the slow query. My email is in my profile, you can mangle the views/tables/columns names before dumping the schema if you like.

**Comment by barbalex** [comment]
@steve-chavez Never mind the incoveniences: postgrest and postgraphql are saving me from having to build a backend on my own. Thanks a lot for pushing this great project! Structure coming in email.

**Comment by steve-chavez** [comment]
@barbalex Thanks for providing your db structure, I've tried it and it took around 8 mins for PostgREST to start, with the change in #1115 it takes around 22 seconds, if you want to try that out you could fetch the PR and build from source, instructions here https://postgrest.org/en/v4.4/install.html#build-from-source.

**Comment by barbalex** [comment]
@steve-chavez I'd rather not try to test this yet: I work on Windows and it looks like it might be a bit of a challenge for me to build from source.

Will https://github.com/PostgREST/postgrest/pull/1115 be merged anyway? I'd gladly test afterwards.

**Comment by barbalex** [comment]
@steve-chavez Thanks a lot for testing!

**Comment by steve-chavez** [comment]
I've discarded the old query and added a new one(backwards compatible) that finishes in about 400 milliseconds using barbalex's schema.

Would like to double check before I merge this new query, @ejdoming @krueger71 @barbalex could you share your results of running the following query?(replace `'exposed_schema'` with your big schema)
```sql
explain analyze with
views as (
  select
    n.nspname   as view_schema,
    c.relname   as view_name,
    r.ev_action as view_definition
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  join pg_rewrite r on r.ev_class = c.oid
  where (c.relkind = 'v'::char) and n.nspname = 'exposed_schema'
),
removed_subselects as(
  select
    view_schema, view_name,
    regexp_replace(view_definition, ':subselect {.*?:constraintDeps <>} :location', '', 'g') as x
  from views
),
target_lists as(
  select
    view_schema, view_name,
    regexp_split_to_array(x, 'targetList') as x
  from removed_subselects
),
last_target_list_wo_tail as(
  select
    view_schema, view_name,
    (regexp_split_to_array(x[array_upper(x, 1)], ':onConflict'))[1] as x
  from target_lists
),
target_entries as(
  select
    view_schema, view_name,
    unnest(regexp_split_to_array(x, 'TARGETENTRY')) as entry
  from last_target_list_wo_tail
),
results as(
  select
    view_schema, view_name,
    substring(entry from ':resname (.*?) :') as view_colum_name,
    substring(entry from ':resorigtbl (.*?) :') as resorigtbl,
    substring(entry from ':resorigcol (.*?) :') as resorigcol
  from target_entries
)
select
  sch.nspname as table_schema,
  tbl.relname as table_name,
  col.attname as table_column_name,
  res.view_schema,
  res.view_name,
  res.view_colum_name
from results res
join pg_class tbl on tbl.oid::text = res.resorigtbl
join pg_attribute col on col.attrelid = tbl.oid and col.attnum::text = res.resorigcol
join pg_namespace sch on sch.oid = tbl.relnamespace
where resorigtbl <> '0'
order by view_schema, view_name, view_colum_name;
```

**Comment by barbalex** [comment]
409 milliseconds :-)

**Comment by barbalex** [comment]
409 milliseconds was on my local machine. It takes 4 to 5 seconds on the live server, which still is great

**Comment by steve-chavez** [comment]
#1115 Got merged, so closing.

Thanks a lot @barbalex, without your help this issue couldn't have been solved.

@all Consider supporting [PostgREST on Patreon](https://www.patreon.com/postgrest) if you'd like to compensate me for the time/effort I put on for solving this, that would also ensure PostgREST keeps getting better in a sustained manner.
